### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by aWeinzierl** [improbable-eng/ts-protoc-gen#100]
```
protoc \
	shared\proto\Api.proto \
	--plugin="protoc-gen-ts=$(PROTOC_GEN_TS_PATH)"make \
    	--js_out="import_style=commonjs,binary:$(protoJavascriptPath)" \
	--ts_out=".\" 
```
Whatever path I use in ts_out (" ./", ".\", :$(protoJavascriptPath), no path at all, empty path, "." , with or without quotes), if I use Powershell or a makefile(CMD): I receive the following error: 
`--ts_out: protoc-gen-ts: The system cannot find the path specified.`

Windows x86-64, libprotoc 3.6.1,

Javascript, php outputs just work fine.

**Comment by navono** [comment]
related to [issue 15](https://github.com/improbable-eng/ts-protoc-gen/issues/15), it must be absolute path or add `%CD%`.

**Comment by aWeinzierl** [comment]
works fine, thanks

How about a clue in the readme?

**Comment by navono** [comment]
maybe a PR?
