### ISSUE TITLE
Client grpc_pb.d.ts files not being generated

### ISSUE THREAD

**Issue by sangaman** [improbable-eng/ts-protoc-gen#102]
This doesn't seem to always occur, but recently I've noticed that the grpc client type declarations ending in `grpc_pb.d.ts` are not being generated. The `pb.d.ts` files for the request and response types are being generated, however. Versions are as follows:

libprotoc 3.4.0
nodejs 8.x
ts-protoc-gen 0.6.0 and 0.7.6

On Windows 10 I've seen this issue several times, but running on linux debian stretch with the same .proto definition file and `protoc` version will work fine. A colleague has also reported seeing this issue on MacOS. Right now my workaround is to just generate type declarations on linux.

Here's the command we're using on linux/mac:

`protoc --js_out='import_style=commonjs,binary:lib/proto' --ts_out='import_style=commonjs,binary:lib/proto' --grpc_out='lib/proto' --plugin='protoc-gen-grpc=node_modules/.bin/grpc_tools_node_protoc_plugin' --plugin='protoc-gen-ts=node_modules/.bin/protoc-gen-ts' -I='proto' proto/*.proto proto/google/api/*.proto proto/google/protobuf/*.proto`

And the command for windows:

`protoc --js_out=\"import_style=commonjs,binary:lib\\proto\" --ts_out=\"import_style=commonjs,binary:lib\\proto\" --grpc_out=\"lib\\proto\" --plugin=\"protoc-gen-grpc=node_modules\\.bin\\grpc_tools_node_protoc_plugin.cmd\" --plugin=\"protoc-gen-ts=node_modules\\.bin\\protoc-gen-ts.cmd\" -I=\"proto\" proto\\*.proto proto\\google\\api\\*.proto proto\\google\\protobuf\\*.proto`

**Comment by sangaman** [comment]
We figured this out, it was a result of a conflict which the [grpc_tools_node_protoc_ts](https://www.npmjs.com/package/grpc_tools_node_protoc_ts) package.

**Comment by jonahbron** [comment]
@sangaman I'm running into the same issue.  I've tried removing grpc_tools_node_protoc_ts, but still not getting the `grpc_pb.d.ts` files.  Can you offer any other details on how you resolved this issue?

**Comment by jonahbron** [comment]
After some debugging, I was able to resolve this by actually removing [ts-protoc-gen](http://npmjs.com/package/ts-protoc-gen) and depending entirely on [grpc_tools_node_protoc_ts](https://npmjs.com/package/grpc_tools_node_protoc_ts) for both `_pb.d.ts` and `_grpc_pb.d.ts` files.
