### ISSUE TITLE
vue with ts-protoc-gen has Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by lionelee** [improbable-eng/ts-protoc-gen#103]
When I using the latest version of ts-protoc-gen in my [vue project](https://github.com/lionelee/test-grpcweb-vue) I got Uncaught ReferenceError: exports is not defined.

**Versions as follows:**
Vue 3.0.0-rc.12/ts-protoc-gen 0.7.6/Node 10.7.0/yarn 1.7.0/macOS High Sierra

**Comment by nadilas** [comment]
+1

**Comment by jonnyreeves** [comment]
@lionelee the repo you have linked to 404's for me, is it private? Can anyone provide a minimal repro for me to debug?  Thanks.

**Comment by jonnyreeves** [comment]
Thanks @HuangXiZhou; I think I have a better understanding of this problem now - put simply, the gRPC-Web Service Stubs generated by ts-protoc-gen expect a CommonJS environment/build system (eg: webpack).

It sounds like the ask here is for ts-protoc-gen to support alternate module systems; however I am confused as the original issue states that only the `exports` reference is causing a problem - shouldn't the `require()` call found at the top of each of generated file also be causing problems?

**Comment by tiramiseb** [comment]
I have the exact same problem.
`module` exists but `module.exports` is `undefined`.

When  I put `console.log(module)` at the top of the `xxx_pb_service.js` file after generation, I get:
```
{exports: undefined, webpackPolyfill: 1}
```

So, I have modified your suggestion and am using:
```
var exports = (typeof module === 'object' && module != null && module.exports !== undefined) ? module.exports : {};
```
I don't have this error anymore.

Of course, it also works with:
```
var exports = {};
```

**Comment by tiramiseb** [comment]
I have essentially done what HuangXiZhou suggested above and it works.
I guess it is related to the fact that he does not "have a node style module system present in browser environment" and that I'm in the same situation.

**Comment by jonny-improbable** [comment]
@tiramiseb are you able to provide a repro of your issue?

**Comment by tiramiseb** [comment]
Here it is:
https://github.com/tiramiseb/grpcweb-exportsproblem

**Comment by jonny-improbable** [comment]
Thanks for the repro, it would appear that this vue-loader issue is related: https://github.com/vuejs/vue-loader/issues/1337

**Comment by tiramiseb** [comment]
... which states "module.exports" is not supported anymore (https://github.com/vuejs/vue-loader/issues/1337#issuecomment-402487724)

**Comment by jonny-improbable** [comment]
Wow, that was a fun bit of debugging! TL;DR the service generation code is invoking an ES6 function (`Object.assign`) which is tricking webpack into treating the modules as ES6 modules instead of ES5 modules.

**Comment by jonnyreeves** [comment]
If anyone wants to try this out and give feedback, please update your
dependency on ts-protoc-gen to 0.7.7-pre.687bcc7

**Comment by tiramiseb** [comment]
Tried it. Works perfectly. Thanks!
