### ISSUE TITLE
Support Flow definitions generation ?

### ISSUE THREAD

**Issue by flegall** [improbable-eng/ts-protoc-gen#11]
Hi,

I would like to contribute to this project with a pull request bringing Flow (https://flow.org/) definitions generation. At fluo.com we use protocol buffers too and we use Flow so it would be definitely be helpful !

I was thinking of adding a "_.bin/protoc-gen-flow_" plugin that would output flow definitions just like typescript with proper flow options.

How would you welcome such a PR ?

Regards,

Florent

**Comment by MarcusLongmuir** [comment]
Hi @flegall,

For Flow support to make sense as part of this project I think we would need to clearly separate the language-specific printing from the rest of the export map building and iteration logic. 

Alternatively, it might be simpler to maintain if you fork the project.

If you think that the former option is best, I think it would be best to do the restructuring before adding the additional language support.

Thanks

**Comment by flegall** [comment]
Sure, I also think these the protocol-buffer frontend and the language-specific backends have to be separated. That would be the first thing I'd do.

I'll start working on it next wednesday.

if we really can't merge it, I'll consider forking the project.

Regards,

**Comment by jonnyreeves** [comment]
Closing this issue as we do not plan to directly contribute flow definition generation.  This issue is currently waiting on @flegall -- feel free to re-open.
