### ISSUE TITLE
"Uncaught ReferenceError: exports is not defined" with vue after yarn build

### ISSUE THREAD

**Issue by tiramiseb** [improbable-eng/ts-protoc-gen#111]
Please note this is not the same as #103 .

With ts-protoc-gen v 0.7.7-pre.687bcc7, the problem with XXX_pb_service.js is resolved.

However, when building with `yarn build`, in the browser the same error message appears, related to another file, another line:

```
service_pb.js:300 Uncaught ReferenceError: exports is not defined
    at Module.29fd (service_pb.js:300)
    at s (bootstrap:78)
    at Object.8599 (service_pb_service.js:4)
    at s (bootstrap:78)
    at Module.56d7 (App.vue?685f:2)
    at s (bootstrap:78)
    at Object.0 (bootstrap:151)
    at s (bootstrap:78)
    at r (bootstrap:45)
    at 0 (bootstrap:151)
```

No particular error when executing `yarn build`.

**Comment by tiramiseb** [comment]
Repo is here:
https://github.com/tiramiseb/grpcweb-exportsproblem/tree/exports_after_build

**Comment by riku179** [comment]
In my case, same issue is resolved both dev  and prod environments by using `0.7.7-pre.687bcc7` and adding `"allowSyntheticDefaultImports": true` in `tsconfig.json`

**Comment by tiramiseb** [comment]
@riku179 could you please tell more about `tsconfig.json`?

I don't have a `tsconfig.json` in my source code, I'm directly programming in js, I don't know if it's related or if you're maybe talking about the `tsconfig.json` file in ts-protoc-gen.

**Comment by jonnyreeves** [comment]
Just spent some time debugging this issue; I've not found a solution, however I have identified that removing the contents of the `webapp/babel.config.js` removes the error.

This may help narrow the problem down to the contents of the [@vue/babel-preset-app](https://www.npmjs.com/package/@vue/babel-preset-app) package, but I'm afraid I don't have the time to dig further at this point.

The only real lead I have at this point are threads like [this](https://github.com/vuejs/vue-cli/issues/2500) which hint that you cannot mix module systems in Webpack 4.

**Comment by tiramiseb** [comment]
Thanks a lot for trying to debug this!

My project will be on standby for a few days/weeks, I will then try with this workaround, to see if there is any drawback, and maybe understand how/why this happens.
