### ISSUE TITLE
need some help for: "--ts_out: protoc-gen-ts: The system cannot find the path specified." Thanks

### ISSUE THREAD

**Issue by bpxlion** [improbable-eng/ts-protoc-gen#114]
Hi,

I run the command in CMD on Windows as follows:

protoc.exe --plugin=protoc-gen-ts="c:\Users\xyy\node_modules\bin\protoc-gen-ts" --js_out=import_style=commonjs,binary:. --ts_out=. test.proto

and it complains:

--ts_out: protoc-gen-ts: The system cannot find the path specified.

Could you help to point what I am missing? Thanks a lot :)

**Comment by jonnyreeves** [comment]
Shouldn't that be `node_modules\.bin\` (note the `.` before 'bin'

**Comment by jonny-improbable** [comment]
Hi @bpxlion I've closed this issue as there has been no response in over 2 weeks; please feel free to follow up if you are still having problems.

**Comment by aca-pulco** [comment]
Me same issue
--ts_out: protoc-gen-ts: The system cannot find the path specified.
