### ISSUE TITLE
Convert Protobuf object to Json and back to Object

### ISSUE THREAD

**Issue by deeshank** [improbable-eng/ts-protoc-gen#119]
Hi,

I was wondering if one could convert the protobuf object to JSON and reconstruct back to the protobuf object. This was possible for python using Google protobuf library.

Thanks

**Comment by jonny-improbable** [comment]
I believe this is a dupe of #9

**Comment by aWeinzierl** [comment]
I believe he means JSON as string instead of binary.
Currently, there is only the binary format afaik.

**Comment by aWeinzierl** [comment]
*activity*

**Comment by jonny-improbable** [comment]
@aWeinzierl do you have a suggestion for how we can move this issue forward?

**Comment by cprovatas** [comment]
_*activity*_
