### ISSUE TITLE
Missing path attribute in service class - adding service to the grpc server

### ISSUE THREAD

**Issue by ibrahimduran** [improbable-eng/ts-protoc-gen#12]
I'm trying to add my service class to grpc.Server but it throws the `Method handler for undefined already provided.` error. Apparently the [path](https://github.com/grpc/grpc/blob/master/examples/node/static_codegen/helloworld_grpc_pb.js#L49) attribute doesn't exist on service classes.

**Comment by MarcusLongmuir** [comment]
Hi @ibrahimduran. `ts-protoc-gen` outputs the `d.ts` files that match the JS generated by `protoc --js_out`, but the service definitions are for [improbable-eng/grpc-web](https://github.com/improbable-eng/grpc-web), not [grpc/grpc](https://github.com/grpc/grpc/tree/master/src/node).

I'm sure this project would welcome a PR to add additional support for the [grpc/grpc](https://github.com/grpc/grpc/tree/master/src/node) service definitions though.
