### ISSUE TITLE
Add support for non-nullable properties

### ISSUE THREAD

**Issue by Ky6uk** [improbable-eng/ts-protoc-gen#120]
`gogoproto.nullable` annotation allow us to control property availability

For example the code 

```proto
message Example {
    TestMessage test = 1 [(gogoproto.nullable) = false];
}
```

will generate TS

```ts
export class Example extends jspb.Message {
  getTest(): TestMessage | undefined;

  // ...
}
```

when `getTest()` actually will never return `undefined`. And it will require additional checks to `undefined` in codebase when `strictNullChecks` is enabled.

So can we add a custom annotation which will generate TS code without `| undefined` part? Or please guide me how I can control this behaviour.

**Comment by easyCZ** [comment]
`gogoproto.nullable` is a proto extension. Your usage in this context is domain specific, ie. only the receiver implementing gogoproto will know what this means. However, `ts-protoc-gen` does not understand this extension.

Furthermore, the fundamental proto message can still be null, it is just your particular domain that is claiming it never will be.

It might be possible to fork this repo and implement the extension. At the moment, we don't have sufficient support for plugins

**Comment by stefanorinetti** [comment]
As far as I am aware every message property in `proto3` is `required`.

```proto
message A {
  B test = 1;
}

message B {
  string val = 1;
}
```

Generates the following  (I'm pasting only part of it)

```typescript
export class A extends jspb.Message {
  hasValue(): boolean;
  clearValue(): void;
  getValue(): B | undefined;
  setValue(value?: B): void;

  // ...
}
```



```typescript
export namespace A {
  export type AsObject = {
    value?: B.AsObject,
  }
}
```

What's the deal with having `| undefined` in the class properties?

The same goes for the `.AsObject` properties.

**Comment by Ky6uk** [comment]
@stefanorinetti All fields inside a message are required actually. You can omit any of them and default value will be set. https://developers.google.com/protocol-buffers/docs/proto3#default
