### ISSUE TITLE
Issues in binary wire serialisation

### ISSUE THREAD

**Issue by jacobfederer** [improbable-eng/ts-protoc-gen#136]
When serialising my protos on the client side and sending them to my server, which is written in go and using the standard way of deserialising the data back, it fails due to the fact that the incoming data is not formatted in the right way. This is the deserialisation error:`proto: can't skip unknown wire type 4`. 

The way I serialise code on the client is as follows.

```
 login(authCredentials: AuthCredentials): Observable<AuthResponse> {

    const credentials = new AuthCred();

    credentials.setEmail(authCredentials.email);
    credentials.setPassword(authCredentials.password);

    const out = credentials.serializeBinary();

    return this.http.post('http://localhost:8080/login', out.toString(), {
        headers: {
          'Content-Type': 'application/protobuf',
          'Accept': 'application/protobuf'
        }
        , responseType: 'arraybuffer'
      }
    )
      .pipe(map((response: ArrayBuffer) => {
        return AuthResponse.deserializeBinary(new Uint8Array(response));
      }));
  }
```

My server side deserialisation code looks like this: 

```
func GetTokenHandler(ctx context.Context, w http.ResponseWriter, r *http.Request) {

	body, err := readBody(r)
	out := &*protopackage*.AuthResponse{}

	authCredentials := &*protopackage*.AuthCred{}

	if err = proto.Unmarshal(body, authCredentials); err != nil {
		WriteDefaultBadRequestErrorResponse(ctx, w, out)
		fmt.Printf("Failed with the following error: %v", err)
		return
	}
```

Since you reuse a lot of the google serialisation for javascript tools this might also and issue with the dependency. 

Thanks for your help!

**Comment by jacobfederer** [comment]
Any idea on this problem?

**Comment by jacobfederer** [comment]
Another point is when using as an AsObject certain fields have a wrong signature. I currently use AsObject as a workaround to serialise the my proto messages into json. First repeated fields are appended a "List" suffix in the AsObject struct. This can't be understood by other consumers because the actual name in serialised form (the message definition) is without it. Second this also applies to fields with underscore delimiters, because these are translated into camelcase.

**Comment by jonnyreeves** [comment]
Hi @jacobfederer, apologies for the slow response to your question.

I'm afraid I'm not sure where your problem lies from looking at your code snippet, however I am confused by your usage. Why are you choosing to send the request using an http library? I would expect consumers of ts-protoc-gen to use the gRPC service client which gets codegen'd.

As for the naming of fields in the `AsObject` representation, I'm afraid this is beyond the control of ts-protoc-gen and is instead stipulated by protocgen itself.

**Comment by jacobfederer** [comment]
Hi @jonnyreeves,

I decided not to use gRPC in my project, because the API will also be reachable from outside my company. For these users it't just easier to have the JSON fallback and don't be bound gRPC.

Right, got it. So you delegate the complete JS code generation to the google plugin, correct?

**Comment by jonnyreeves** [comment]
Hey @jacobfederer

> I decided not to use gRPC in my project, because ... it's just easier to have the JSON fallback 

That's understandable, although https://github.com/grpc-ecosystem/grpc-gateway may be of interest for future projects.

> So you delegate the complete JS code generation to the google plugin, correct?

Correct. ts-protoc-gen currently serves two functions:

1. Generate TypeScript definitions for the JavaScript generated by protocgen
2. Generate both the JavaScript source code and TypeScript definitions for use with improbable-eng/grpc-web

We are actually looking to split these two functions out into two distinct protoc plugins in the future to help simplify things.
