### ISSUE TITLE
Two maps for enumerations

### ISSUE THREAD

**Issue by azcorp-cloud** [improbable-eng/ts-protoc-gen#143]
Protobuff for C, Go and Java have two maps for every enum (int to string & string to int);
Go
```
type Status int32

const (
	UnknownStatus Status = 0
	Active        Status = 1
	Inactive      Status = 2
)

var Status_name = map[int32]string{
	0: "UnknownStatus",
	1: "Active",
	2: "Inactive",
}
var Status_value = map[string]int32{
	"UnknownStatus": 0,
	"Active":        1,
	"Inactive":      2,
}
```
Is it possible to generate them?
It will be very convenient.

**Comment by jonnyreeves** [comment]
Thanks for raising this issue @azcorp-cloud; however ts-protoc-gen only generates the TypeScript definitions, and grpc service stubs for use with improbable-eng/grpc-web.

If I understand correctly, I believe your issue resides with the underlying javascript code-gen which needs to be raised against the [grpc project](https://github.com/grpc/grpc).
