### ISSUE TITLE
Generate messages cant use getters or setters

### ISSUE THREAD

**Issue by Teo27** [improbable-eng/ts-protoc-gen#150]
we have message inception
```
syntax = "proto3";
import "PositionInfoDto.proto";

message ReportDto {	
	PositionInfoDto positionInfoDto = 2;
	int32 poiId = 3;
	ReportType reportType = 4;
	enum ReportType {
		Unknown = 0;
		Accident = 1;
	
	}
}
```

```
syntax = "proto3";

import "PositionPointDto.proto";

message PositionInfoDto {
	PositionPointDto positionPointDto = 1;
	oneof speedValue {
		double speed = 2; // Speed at which the vehicle is moving
	}
	oneof headingValue {
		double heading = 3; // The direction in which the vehicel is moving
	}
	oneof locationAccuracyValue {
		double locationAccuracy = 4; // Accuracy of the GPS location
	}
}
```

```
syntax = "proto3";
message PositionPointDto {
	oneof latitudeValue { 
		double latitude = 1;
	}
	oneof longitudeValue {
		double longitude = 2;
	}
}
```

The generated result is:
```
import * as jspb from "google-protobuf";

import * as PositionInfoDto_pb from "./PositionInfoDto_pb";

export class ReportDto extends jspb.Message {
  hasPositioninfodto(): boolean;
  clearPositioninfodto(): void;
  getPositioninfodto(): PositionInfoDto_pb.PositionInfoDto | undefined;
  setPositioninfodto(value?: PositionInfoDto_pb.PositionInfoDto): void;

  getPoiid(): number;
  setPoiid(value: number): void;

  getReporttype(): ReportDto.ReportType;
  setReporttype(value: ReportDto.ReportType): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): ReportDto.AsObject;
  static toObject(includeInstance: boolean, msg: ReportDto): ReportDto.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: ReportDto, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): ReportDto;
  static deserializeBinaryFromReader(message: ReportDto, reader: jspb.BinaryReader): ReportDto;
}

export namespace ReportDto {
  export type AsObject = {
    positioninfodto?: PositionInfoDto_pb.PositionInfoDto.AsObject,
    poiid: number,
    reporttype: ReportDto.ReportType,
  }

  export enum ReportType {
    UNKNOWN = 0,
    SPEEDCONTROL = 1,
    ACCIDENT = 2,
    HARDSHOULDER = 3,
    OBJECTONTHEROAD = 4,
    CONGESTION = 5,
    UNKNOWNINCIDENT = 6,
  }
}

```

the problem that when we try to access properties of the object.
The current case requires us to use SignalR with json, and when we receive the object just specify that is of they ReportDto. That works, fine. when i console log the object i can see all the properties.

So lets try to access the ID
   console.log(data.getId());
this results in:

ERROR TypeError: data.getId is not a function

then I try to get the id property:
     console.log(data.id)
this compiles and actually gives me the result

how in the IDE i get:
ERROR in src/app/shared/some-service.service.ts(81,24): error TS2339: Property 'id' does not exist on type 'ReportDto'.

This issue looks similar to : https://github.com/improbable-eng/ts-protoc-gen/issues/89

The Exact comand for generating our DTO that we use is:
protoc --proto_path="< folder proto files are located >"  --plugin=protoc-gen-ts="C:\Users\<my user>\AppData\Roaming\npm\protoc-gen-ts.cmd" --ts_out="C:/Users/< my user >/angular-dto"  "< exact path to DTO >\ReportDto.proto"

**Comment by ivan-penchev** [comment]
Interesting, we had the same problem. We switched to protojs, but that is not the slickest solution. @jonnyreeves  can you help?

**Comment by jonny-improbable** [comment]
Hey @Teo27 thanks for providing a repro case; I've raised #151 which tries to reproduce this issue without success; please could you let me know what differs between our setups?

You can pull the `bugfix/150` branch down from the repo, and issue the following commands to debug:

```
./generate.sh
npm t
```

Thanks

**Comment by jonny-improbable** [comment]
Closing this issue as we were not able to create a repro.
