### ISSUE TITLE
Server Streams `onStatus` happens after `onEnd`, would expect the reverse

### ISSUE THREAD

**Issue by hectim** [improbable-eng/ts-protoc-gen#155]
**Versions of relevant software used**
0.9.0

**What happened**
I am writing a promise wrapper around the generated grpc client requests. I thought it made sense to resolve the promise inside the `onEnd` handler, but found that if my call failed it would hit the `onEnd`, resolve the promise, and then get a status code other than 0 (meaning my call actually failed).

**What you expected to happen**
I would expect the `end` handler to be called very last. Additionally, I believe it would be nice to pass the status to the `end` handler. Since the current implementation doesn't take any parameters, adding an optional status parameter should be a pizza cake. 

**How to reproduce it (as minimally and precisely as possible)**:
```typescript
const streamRequest = myClient.myRequest();
streamRequest.on('status', () => console.log('happens second'));
streamRequest.on('end', () => console.log('happens first'));
await streamRequest;
```

***

Am I missing something major here or was it just a small implementation detail? Would you be open to a PR that essentially just swaps the order the listeners are called in the onEnd?
```typescript
onEnd: function (status, statusMessage, trailers) {
  listeners.end.forEach(function (handler) {
    handler();
  });
  listeners.status.forEach(function (handler) {
    handler({ code: status, details: statusMessage, metadata: trailers });
  });
  listeners = null;
}
```
and updates the end types for an optional parameter from this:
``` typescript
on(type: 'end', handler: () => void): ResponseStream<T>;
```
to this:
```typescript 
on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
```

**Comment by jonnyreeves** [comment]
Sorry for the slow response @hectim. Yes to both of these things please :)
