### ISSUE TITLE
Handling of enums

### ISSUE THREAD

**Issue by mattvagni** [improbable-eng/ts-protoc-gen#156]
I've noticed something quite strange about the handling of enums, I'm not sure what the solution is but am happy to help contribute a fix once decided what the correct behaviour should be (and whether this is even an issue).

Assuming an enum in proto file like this:

```proto
enum Emotion {
  POSITIVE = 0;
  NEUTRAL = 1;   
  NEGATIVE = 2; 
}
```

The typescript generation will output:

```tsx
enum Emotion {
  POSITIVE = 0,
  NEUTRAL = 1,   
  NEGATIVE = 2, 
}
```

The matching javascript output is:

```js
/**
 * @enum {number}
 */
proto.stock.Emotion = {
  POSITIVE: 0,
  NEUTRAL: 1,
  NEGATIVE: 2,
};
```

### The problem

The problem is that typescript enums should actually be outputted like so in javascript: 

```js
var Emotion;
(function (Emotion) {
    Emotion[Emotion["POSITIVE"] = 0] = "POSITIVE";
    Emotion[Emotion["NEUTRAL"] = 1] = "NEUTRAL";
    Emotion[Emotion["NEGATIVE"] = 2] = "NEGATIVE";
})(Emotion || (Emotion = {}));
```

This resulting value of the `Emotion` var becomes this once the above code is evaluated:

```js
var Emotion = {
  0: "POSITIVE"
  1: "NEUTRAL"
  2: "NEGATIVE"
  NEGATIVE: 2
  NEUTRAL: 1
  POSITIVE: 0
}
```

This allows for mapping in both directions so that [both of these would be truthy](https://www.typescriptlang.org/play/#src=enum%20Emotion%20%7B%0D%0A%20%20POSITIVE%20%3D%200%2C%0D%0A%20%20NEUTRAL%20%3D%201%2C%20%20%20%0D%0A%20%20NEGATIVE%20%3D%202%2C%20%0D%0A%7D%0D%0A%0D%0Aconsole.log(Emotion%5B0%5D%20%3D%3D%3D%20'POSITIVE')%3B%0D%0Aconsole.log(Emotion.POSITIVE%20%3D%3D%3D%200)%3B):

```js
console.log(Emotion[0] === 'POSITIVE');
console.log(Emotion.POSITIVE === 0);
```

If we treat the javascript output from protoc as correct it means that potentially this plugins' handling of proto enums should be different.

### Potential solutions

**1. Output type definitions that match the outputted javascript**

I think this could be as simple as making enums be outputted like this in typescript:

```tsx
interface Emotion {
  0: "POSITIVE";
  1: "NEUTRAL";
  2: "NEGATIVE";
  POSITIVE: 0;
  NEUTRAL: 1;
  NEGATIVE: 2; 
}
```

**2. Document this limitation of enums**

We could very clearly say that this is the case in the documentation and the generated code?

----

Happy to propose/work on a solution once an approach has been decided upon and thanks for providing such a great library 👍

**Comment by jonnyreeves** [comment]
Hi @mattvagni, thank you for providing such a detailed pull request and volunteering to help with the fix.

One of the goals of ts-protoc-gen is to provide TypeScript interfaces which match the javascript generated by the javascript protoc plugin. As a result I view this as a bug in our implementation (ie: we should not be generating enums, but instead an `interface` as you've suggested).

Looking at the generated code (eg: [external_enum_pb.js](https://github.com/improbable-eng/ts-protoc-gen/blob/master/examples/generated/proto/othercom/external_enum_pb.js#L18)), it looks like we should only provide a one-way mapping, ie:

```typescript
interface ExternalEnum {
  DEFAULT: 0
  FIRST: 1
  SECOND: 2
}
```

**Comment by mattvagni** [comment]
@jonnyreeves That makes sense - got mixed up in my solution, you are right: we **don't** want to support a two way mapping. Will have a go at doing that. Should be fairly straight-forward I think 👍

**Comment by mattvagni** [comment]
@jonnyreeves I'm not sure how to best define the messages. If you do this for example: 

```diff
 export class EnumMessage extends jspb.Message {
-  getInternalEnum(): EnumMessage.InternalEnum;
-  setInternalEnum(value: EnumMessage.InternalEnum): void;
+  getInternalEnum(): EnumMessage.InternalEnum[keyof EnumMessage.InternalEnum];
+  setInternalEnum(value: EnumMessage.InternalEnum[keyof EnumMessage.InternalEnum]): void;
```

to essentially say that you must essentially provide a 'value' of the proto's enum the authoring experience becomes a bit rubbish since IDEs basically just list out numbers like this:

<img width="636" alt="Screenshot 2019-03-29 at 22 25 27" src="https://user-images.githubusercontent.com/1372762/55265749-953b8a00-5271-11e9-9853-b11c9cf52b17.png">

instead of this:

<img width="722" alt="Screenshot 2019-03-29 at 22 27 53" src="https://user-images.githubusercontent.com/1372762/55265848-f19ea980-5271-11e9-94a9-133a518aa235.png">


It's definitely 'accurate' but i'm wondering if there is something we can do to make this nicer - any thoughts?

**Comment by jonny-improbable** [comment]
Fixed in #157; open question around type-hints still stands if anyone knows a better way?

**Comment by avishco1** [comment]
Hi,

i haven't figured out yet how to use this new mapping structure.
Say the generated code is:
![image](https://user-images.githubusercontent.com/7114793/86562736-dbe75c00-bf6b-11ea-8819-f99858050573.png)

1. How can an uninitialized const be exported? if I copy this code to some TS file, it will not compile ('const' declarations must be initialized)
2. How do I consume this?
This code generates errors
![image](https://user-images.githubusercontent.com/7114793/86563149-895a6f80-bf6c-11ea-8552-52717c9b54b0.png)

thanks!

**Comment by mattvagni** [comment]
HI @avishco1 This package only generates the types. You will still need to generate the actual javascript client (where the const will then actually be defined). You can do this using the javascript protoc plugin.

**Comment by doom-goober** [comment]
@mattvagni @avishco1 Assuming I have:
```
enum AnimalType {
  None = 0;
  Bird = 1;
  Dog = 2;
}
```

And I generate both the JS and the TS using protoc, the only way I've figured out how to use use it with proper type safety is:

```
import {AnimalType, AnimalTypeMap} from "./generated/AnimalType_pb"
const someAnimal:AnimalTypeMap[keyof AnimalTypeMap] = AnimalType.Bird;
```

This works, however it's very clunky. Am I doing something wrong? Thanks.

**Comment by jesseschalken** [comment]
@doom-goober I don't think so. You can define

```typescript
type AnimalTypeValue = AnimalTypeMap[keyof AnimalTypeMap]
```

and use that if you prefer.
