### ISSUE TITLE
Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

### ISSUE THREAD

**Issue by ashi009** [improbable-eng/ts-protoc-gen#164]
As seen in 
https://github.com/improbable-eng/ts-protoc-gen/blob/53aa49ccb3fa7832934ff1cbf86ec62df1cde4cd/src/index.ts#L48

`new Buffer()` is still used.

> (node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by jonnyreeves** [comment]
Thanks for raising this issue, would you be able to contribute a fix,
please?
