### ISSUE TITLE
MacOS: Sed errors when building on mac

### ISSUE THREAD

**Issue by strican** [improbable-eng/ts-protoc-gen#166]
**Versions of relevant software used**

macOS 10.14.4
Bazel 0.22.0
Building from [commit cdb79ec](https://github.com/improbable-eng/ts-protoc-gen/commit/cdb79ecf85a0ea08b86cf98860c2d42ffcc18d20). 

**What happened**

Building a `typescript_proto_library` fails on MacOS. Relevant output below in logs.

**What you expected to happen**

Build successfully.

**How to reproduce it (as minimally and precisely as possible)**:

On MacOS, clone the latest version of master.
Run `bazel build ...`

**Full logs to relevant components**

<details>Logs
<p>

```Bash
ts-protoc-gen (mac-sed-errors)$ bazel build ...
INFO: Invocation ID: 99cd2517-8b10-4318-8fb6-c705b3531199
DEBUG: /private/var/tmp/_bazel_steventricanowicz/9873f923b91e630355f329e396f67465/external/bazel_skylib/skylark_library.bzl:1:1: WARNING: skylark_library.bzl is deprecated and will go away i
n the future, please use bzl_library.bzl instead.
INFO: Analysed 24 targets (7 packages loaded, 112 targets configured).
INFO: Found 24 targets...
ERROR: /Users/steventricanowicz/source/ts-protoc-gen/proto/othercom/BUILD.bazel:9:1: error executing shell command: '/bin/bash -c bazel-out/host/bin/external/com_google_protobuf/protoc --plu
gin=protoc-gen-ts=bazel-out/host/bin/external/ts_protoc_gen/bin/protoc-gen-ts --ts_out=service=true:bazel-out/darwin-fastbui...' failed (Exit 1) bash failed: error executing command /bin/bas
h -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
sed: 1: "bazel-out/darwin-fastbu ...": undefined label 'azel-out/darwin-fastbuild/bin/proto/othercom/external_child_message_pb.js'
INFO: Elapsed time: 37.497s, Critical Path: 31.88s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

</p>
</details>

**Anything else we need to know**

This seems to be because the MacOS version of sed differs from that on Linux. There needs to be platform-dependent code in the aspects. It seems like it's totally broken on everything but Linux since [commit 14d69f6](https://github.com/improbable-eng/ts-protoc-gen/commit/14d69f6203c291f15017a8c0abbb1d4b52b00b64).

**Comment by strican** [comment]
@Dig-Doug, can you verify that you're only building on Linux?

**Comment by Dig-Doug** [comment]
Yes, I'm only building on linux.

I agree that it looks like the commands [here](https://github.com/improbable-eng/ts-protoc-gen/blob/master/defs.bzl#L56) are the cause. It probably makes sense to move those transformations into a tool, e.g. a node script, so that it will work on other platforms. If you've got some time to look into it, [here's an example](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run) :)

**Comment by easyCZ** [comment]
@Dig-Doug's analysis makes sense. Would you be open to raising a PR?

**Comment by strican** [comment]
Yeah, I've got a fix that works but obviously that breaks it on Linux. I've been looking at the best way to do it. Unless there's an existing node module for AMD generation, I may not have the time to go with that approach. For now it seems like using a `sh_binary` and moving that code to platform-specific scripts would be easiest. What do you think?

**Comment by strican** [comment]
@Dig-Doug, I'm curious why you included it in #138. It doesn't seem necessary on the surface and it's the only thing that's breaking. I think some context there would be helpful for me. My only guess is that it's necessary for the aspect dependency graph, but that should be coming from Bazel.

If that's true, I think we should split up the AMD module generation.

1. We're modifying the generated files of a rule, so those should be inputs into another rule.
2. The modifications are only happening for the JS files, so they're not strictly relevant to the typescript rule. An `javascript_proto_library` and/or a `javascript_module_proto_library` would give people finer-grained control over what they want.
3. The module generation code needs to be its own binary so it can be platform-constrained (or compiled based on the host platform).
4. It's the only thing that's breaking.

Splitting it out and/or disabling this gets us to a quick fix. I'm blocked on this and frankly I'm not an expert in any of this technology. Any proper fix would be a pretty significant time investment, and one that's hard to just for my team considering we're only using the TypeScript parts of this rule.

Do you agree with this approach?

**Comment by strican** [comment]
Hopes and dreams (rightfully) dashed in the PR. Back here to follow up on @Dig-Doug's comment.

I did edit the sed commands locally. That gets it to work on my machine, but it's not something I'd feel comfortable pushing. Maybe we can merge it into a second branch that consumers can then point to? It's an easier change than needing to clone the repo, edit the sed commands, and then switch it to point to a local repo.

Alternatively, we could maybe just point to a significantly older commit, but I hesitated to do that because it seemed like the dependency tracking of the aspect provided significant benefits.

To be clear, I would like to get a real fix in here, but given my (clear) lack of knowledge in this area, I don't think that'll happen in any time frame that works. So would you recommend either of the above solutions?

**Comment by Dig-Doug** [comment]
One thing you can do temporarily is push (no PR needed) you fix in a branch on your fork and then point to it in your project's `WORKSPACE`. Something like this:

```
http_archive(
    name = "rules_foreign_cc",
    sha256 = "37f528946bd3bdd4e8248a925059722acbead90c24c62257124e7a1e2098d4aa",
    strip_prefix = "rules_foreign_cc-858fcdda7ad749c3726833464ed3128792db7921",
    urls = [
        "https://github.com/Dig-Doug/rules_foreign_cc/archive/858fcdda7ad749c3726833464ed3128792db7921.tar.gz",
    ],
)
```

If you're working alone, you can also just use a `local_repository`. 

I'll see if I can find some time to fix this over the weekend. I'll post here if I start working on it.

**Comment by strican** [comment]
Pausing this for now while I call in some backup. If I can get a real solution by EOD Monday, then everyone is happy. If not, I'll look to do one of the solutions above.

**Comment by RNabel** [comment]
Just for context, we'll try to identify a future-proof solution to this problem, and are planning to try using a [Bazel Toolchain](https://docs.bazel.build/versions/master/toolchains.html) to select on the type of `sed` command to run on each platform.

**Comment by Dig-Doug** [comment]
I took a stab at fixing this in https://github.com/improbable-eng/ts-protoc-gen/pull/168

I don't have a macOS device, so if you could test it out and make sure it works that would be great :)

**Comment by RNabel** [comment]
Nice! Just checked your changes on macOS 10.14 and it builds successfully 🎉 The repo also builds at HEAD (cdb79ec), however, since I'm my `sed` on the path is a copy of `gsed`:
```
$ sed --version
sed (GNU sed) 4.4
```

**Comment by strican** [comment]
Also confirming it works for me. Thanks, @Dig-Doug!
