### ISSUE TITLE
Please choose a package manager

### ISSUE THREAD

**Issue by bfmiv** [improbable-eng/ts-protoc-gen#171]
Lockfiles are currently (and will likely always be) out of sync. Please let me know which package manager you prefer to use going forward and I'd be happy to open a PR with the necessary changes.

**Versions of relevant software used**
- `node@10.15.3`
- `npm@6.9.0`
- `yarn@1.15.2`
- `ts-protoc-gen@0.9.1-pre (master)`

**What happened**
- `npm install` results in changes to `package-lock.json` and reports several known vulnerabilities in dependency packages

    ```
    added 465 packages from 1179 contributors and audited 2818 packages in 6.933s
    found 5 vulnerabilities (4 moderate, 1 high)
    ```
  <details>
    <summary><code>=== npm audit security report ===</code></summary>
    <br/>
    <pre><code># Run npm install --save-dev @bazel/karma@0.27.12 to resolve 2 vulnerabilities
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Moderate      │ Prototype Pollution                                          │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ lodash                                                       │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ @bazel/karma [dev]                                           │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ @bazel/karma > karma > log4js > streamroller > lodash        │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/782                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  <br/>
  <br/>
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Moderate      │ Prototype Pollution                                          │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ lodash                                                       │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ @bazel/karma [dev]                                           │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ @bazel/karma > karma-sauce-launcher > sauce-connect-launcher │
  │               │ > lodash                                                     │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/782                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  <br/>
  <br/>
  # Run npm install --save-dev lodash@4.17.11 to resolve 1 vulnerability
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Moderate      │ Prototype Pollution                                          │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ lodash                                                       │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ lodash [dev]                                                 │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ lodash                                                       │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/782                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  <br/>
  <br/>
  # Run npm update js-yaml --depth 2 to resolve 2 vulnerabilities
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ Moderate      │ Denial of Service                                            │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ js-yaml                                                      │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ tslint [dev]                                                 │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ tslint > js-yaml                                             │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/788                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
  <br/>
  <br/>
  ┌───────────────┬──────────────────────────────────────────────────────────────┐
  │ High          │ Code Injection                                               │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Package       │ js-yaml                                                      │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Dependency of │ tslint [dev]                                                 │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ Path          │ tslint > js-yaml                                             │
  ├───────────────┼──────────────────────────────────────────────────────────────┤
  │ More info     │ https://npmjs.com/advisories/813                             │
  └───────────────┴──────────────────────────────────────────────────────────────┘
    </code></pre>
  </details>
- `yarn install` prints

    ```
    warning package-lock.json found. Your project contains lock files generated by
    tools other than Yarn. It is advised not to mix package managers in order to
    avoid resolution inconsistencies caused by unsynchronized lock files. To clear
    this warning, remove package-lock.json.
    ```

**What you expected to happen**
- A single source of record for dependency resolutions

**Comment by jonny-improbable** [comment]
Thanks for raising @bfmiv; this issue is caused by the fact that our Bazel build rules rely on yarn, where's the day-to-day development uses npm; I can certainly see how this causes a problem.

My own personal preference is to stick with npm, however removing yarn would break the Bazel build. @Dig-Doug - do you know if the bazel tooling now supports npm? If so, could we consider switching to use it and remove the yarn config?

If this is not possible (or time consuming); then I can switch to yarn - but it would be good to check first.

**Comment by Dig-Doug** [comment]
Here's the [issue](https://github.com/bazelbuild/rules_nodejs/issues/416) with npm. I tried reproducing it today and it still exists.

The bazel team also has a few other reasons for preferring yarn listed [here](https://github.com/bazelbuild/rules_nodejs/issues/403).

**Comment by jonny-improbable** [comment]
Yarn configuration has been removed from this repo which means this issue is now resolved.
