### ISSUE TITLE
path with * fails

### ISSUE THREAD

**Issue by bdparrish** [improbable-eng/ts-protoc-gen#172]
**Versions of relevant software used**

google-protobuf: ^3.7.1
ts-protoc-gen: ^0.9.0
typescript: ~2.7.2

**What happened**

________________________________________________________________________________
| => protoc --proto_path="../../protobuff/" \
  --plugin="protoc-gen-ts=./node_modules/ts-protoc-gen/bin/protoc-gen-ts" \
  --js_out="import_style=commonjs,binary:./src" \
  --ts_out="./src" \
  models/*.proto

models/*.proto: No such file or directory

**What you expected to happen**

I expected the wildcard character to find all .proto extension files for processing.

**How to reproduce it (as minimally and precisely as possible)**:

Unknown

**Full logs to relevant components**

**Anything else we need to know**

**This worked - I gave it the explicit filename**
protoc --proto_path="../../protobuff/" \
  --plugin="protoc-gen-ts=./node_modules/ts-protoc-gen/bin/protoc-gen-ts" \
  --js_out="import_style=commonjs,binary:./src" \
  --ts_out="./src" \
  models/customer.proto

**Comment by jonny-improbable** [comment]
Sorry for the slow response, this is a not an issue with the `ts-protoc-gen` package, but instead a limitation of the `protoc` tool.

May I suggest you consider using [prototool](https://github.com/uber/prototool/) which provides a nice abstraction over `protoc`.
