### ISSUE TITLE
No release tag in a while

### ISSUE THREAD

**Issue by fantapop** [improbable-eng/ts-protoc-gen#174]
Hey, I'd love to get the fix for adding google-protobuf as a runtime dependency put into a release.

**Comment by esilkensen** [comment]
+1, that would be great!

**Comment by jonny-improbable** [comment]
Sorry for the delay; just starting the release of 0.10.0 now. Will be published as soon as I can get a decent Internet connection :)

**Comment by jonny-improbable** [comment]
The release has now been pushed; Travis should publish 0.10.0 to NPM within the next few hours (there's a bit of a backlog at present)

**Comment by jonny-improbable** [comment]
https://www.npmjs.com/package/ts-protoc-gen/v/0.10.0 has now been published.
