### ISSUE TITLE
Reusing message names can result incorrect generated code

### ISSUE THREAD

**Issue by euank** [improbable-eng/ts-protoc-gen#176]
**Versions of relevant software used**

* `ts-protoc-gen@0.10.1-pre.987f176` (from `npm install ts-protoc-gen@next`)
* `protoc --version: libprotoc 3.6.1`

**What happened**

Typescript compilation errors for the generated typescript code when using a valid proto.

**How to reproduce it (as minimally and precisely as possible)**:

```proto
// file: proto/test.proto 
syntax = "proto3";

package test;

message Foo {
  message Bar {
    int32 baz = 1;
  }
}

message Baz {
  message Foo {
    .test.Foo.Bar bar = 1;
  }
}
```

```
$ protoc --plugin="protoc-gen-ts=./node_modules/.bin/protoc-gen-ts" \
    --js_out="import_style=commonjs,binary:out" \
    --ts_out="out" proto/test.proto

$ tsc ./out/proto/test_pb.d.ts
                                                                                                       
out/proto/test_pb.d.ts:60:19 - error TS2694: Namespace '"out/proto/test_pb".Baz.Foo' has no exported member 'Bar'.

60     getBar(): Foo.Bar | undefined;
                     ~~~
...
```

**Anything else we need to know**

This can be fixed by editing the proto to rename one of the two 'Foo' messages.

The generated code that causes the problem looks like so:

```
export namespace Foo {
  export namespace Bar {
    ...
  }
}

export namespace Baz {
  export namespace Foo {
    export type AsObject = {
      bar?: Foo.Bar.AsObject,
    }
  }
}
```

The `bar?: Foo.Bar` line means to refer to the module-level namespace Foo, but ends up accidentally referring to the namespace it's within incorrectly.

**Comment by jonnyreeves** [comment]
Thanks for the detailed repro steps. I'm pretty swamped with work at
present, is this something you can help me with fixing?

Thank you

**Comment by euank** [comment]
I'm also pretty busy and my typescript knowledge is sparse, at best, so I can't commit to fixing this.
If I find a few spare cycles, I might give it a shot though!
