### ISSUE TITLE
Missing input file & No such file or directory error on --ts_out

### ISSUE THREAD

**Issue by codekidX** [improbable-eng/ts-protoc-gen#186]
**Versions of relevant software used**
`0.10.0`

**What happened**

Error saying 
```
Missing input file.
./gen.sh: line 16: --ts_out=./tscgen: No such file or directory
```
not letting me generate typings.

**What you expected to happen**

Generate typings and not give this error as directory exists and also the proto file.

**How to reproduce it (as minimally and precisely as possible)**:

This is the script I'm running

```bash
# npm install ts-protoc-gen
TS_GEN_PATH="./node_modules/.bin/protoc-gen-ts"
TS_OUT_DIR="./tscgen"

rm -rf gogen/*
rm -rf tscgen/*

# GO OUT
protoc \
    --go_out=gogen LoginResponse.proto

# JS & TS.D OUT
protoc \
    --plugin="protoc-gen-ts=${TS_GEN_PATH}" \
    --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" 
    --ts_out="${TS_OUT_DIR}" LoginResponse.proto
```

The `LoginResponse.proto` only has a `string name=1;` field as I'm just learning how to use protocol buffers.

**Full logs to relevant components**

Will provide any logs you ask currently none.

**Anything else we need to know**

The below command generates `.js` file, it is only when I add `--ts_out` this said error is happening.

```bash
# JS & TS.D OUT
protoc \
    --js_out="import_style=commonjs,binary:${TS_OUT_DIR}"  LoginResponse.proto
```
**EDIT**: typo, actually I didn't mention the `--plugin` while creating js file.

**Environment**:
- OS (e.g. from /etc/os-release): `darwin, MacOs Mojave 10.14`
- Kernel (e.g. `uname -a`): `Darwin Ashishs-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`

**Comment by jonnyreeves** [comment]
Ah interesting, I'm going to guess that ts-protoc-gen is not creating any
missing directories if they don't exist. What happens if you create your
output directory before running protoc?

**Comment by codekidX** [comment]
Hi @jonnyreeves, actually the directory already exists before running as I have mentioned above.

Also tried a couple of things:
- gave abosute path with `"${pwd}/tsgen"` instead of `./tscgen`
- deleting the folder and running the `protoc` then also it showed me the error.
- tried `@next` version of ts-protoc-gen to see if any latest commit had fixed this error

But no luck by doing the above things.

**Comment by jonny-improbable** [comment]
Hey @codekidX, sorry just took a closer look at your shell script, you are missing a `\` at the the end of the `js_out=` line, your script should be changed to read as so:

```
# JS & TS.D OUT
protoc \
    --plugin="protoc-gen-ts=${TS_GEN_PATH}" \
    --js_out="import_style=commonjs,binary:${TS_OUT_DIR}"  \ # <-- this one was missing
    --ts_out="${TS_OUT_DIR}" LoginResponse.proto
```

**Comment by codekidX** [comment]
Holy blip how did I miss this, thanks a lot for pointing my mistake.

**Comment by jonnyreeves** [comment]
No worries, happens to the best of us.
