### ISSUE TITLE
All elements in AsObject optional when using proto2

### ISSUE THREAD

**Issue by lgrunenberg** [improbable-eng/ts-protoc-gen#189]
When using the proto2 syntax all elements in the `AsObject` representation are optional, regardless of whether they are marked as `optional` or `required` in the .proto-file.

This behavior can be seen in the output 
[https://github.com/improbable-eng/ts-protoc-gen/blob/master/examples/generated/proto/examplecom/primitive_message_v2_pb.d.ts](https://github.com/improbable-eng/ts-protoc-gen/blob/master/examples/generated/proto/examplecom/primitive_message_v2_pb.d.ts)
of input file
[https://github.com/improbable-eng/ts-protoc-gen/blob/master/proto/examplecom/primitive_message_v2.proto](https://github.com/improbable-eng/ts-protoc-gen/blob/master/proto/examplecom/primitive_message_v2.proto)

Is this behavior intentional? If so, what is the explanation to that?

**Comment by RyGuy101** [comment]
In case anyone finds it useful, I had the same thought and made a [fork](https://github.com/uas-at-ucla-dependencies/ts-protoc-gen/commit/a48ee6e68f8f27d4c2a35cbb22f4a297a96fc6fa) that makes the appropriate fields required in AsObject types. For the actual class types, it makes sense not to mess with the protobuf API, but I'm only using the AsObject representation for complete messages.

**Comment by ksjogo** [comment]
Yeah, I also need required fields.

**Comment by nitruxa** [comment]
any chance this will be fixed/updated on the main repo? facing same issue now.
