### ISSUE TITLE
Reserved field names need prefixing with pb_

### ISSUE THREAD

**Issue by MarcusLongmuir** [improbable-eng/ts-protoc-gen#19]
Some field names are "reserved" such as `public`. These field names are prefixed with `pb_` by the protoc JS generator. ts-protoc-gen needs to follow these same naming conventions.

**Comment by jonnyreeves** [comment]
@MarcusLongmuir sorry to be a :donut: but could you provide me with a repro pb and I'll look to get a fix in?

Thanks!
