### ISSUE TITLE
List postfix generates an error in c#

### ISSUE THREAD

**Issue by shaeussler** [improbable-eng/ts-protoc-gen#196]
**Versions of relevant software used**
0.10.1-pre

**What happened**
For a repeated field the postfix 'List' is added to the value name in the JSON output.

**What you expected to happen**
No 'List' for repeated fields in the JSON output.

**How to reproduce it (as minimally and precisely as possible)**:

repeated_primitive_message.proto:
message RepeatedPrimitiveMessage {
    repeated string my_string = 1;
}

protoc.exe --plugin=protoc-gen-ts=node_modules/.bin/protoc-gen-ts.cmd --js_out=import_style=commonjs,binary:./generated --ts_out=./generated repeated_primitive_message.proto

test.ts:
import {RepeatedPrimitiveMessage} from "./generated/repeated_primitive_message_pb";
const msg = new RepeatedPrimitiveMessage();
msg.addMyString("Test");
console.log(msg.toObject(false));

Console output:
{ myStringList: [ 'Test' ] }

**Full logs to relevant components**

**Anything else we need to know**

I get an error when deserializing such a JSON string in c#.

**Comment by jonny-improbable** [comment]
Hi @shaeussler - please can you confirm if this issue exists in both the generated javascript (`.js` files) and and/or the TypeScript definitions (`.d.ts` files). Thanks.

**Comment by shaeussler** [comment]
The issue exists also in the generated javascript (.js files).
I found the error in my sample.
The function toObject generates no official JSON format.
See https://github.com/protocolbuffers/protobuf/issues/4518.
In typescript/javascript in the JSON output the name of the repeated field is myStringList in c# the name is MyString.
