### ISSUE TITLE
TS2307: Cannot find module './google/api/annotations_pb'

### ISSUE THREAD

**Issue by Emixam23** [improbable-eng/ts-protoc-gen#201]
I am struggling with this error:

`TS2307: Cannot find module './google/api/annotations_pb'`

In fact, I have this protobuf:

```
syntax = "proto3";

package ChatAPI;

import "google/api/annotations.proto";

option go_package = "ChatAPI";

//
// The Chat API service definition.
//

service ChatAPIService {

    rpc HelloWorld (HelloWorldRequest) returns (HelloWorldResponse) { option (google.api.http) = { post: "/hello_world" body:"*" }; }
}

//
// Chat API service parameters/returns data definition.
//

message HelloWorldRequest {
    string name = 1;
}

message HelloWorldResponse {
    string response = 1;
}

```

My Go backend is working fine for the REST part. I am now connecting my ReactJs TypeScript to my backend, so I generated my TypeScript output of the protobuf:

```
# Path to this plugin 
PROTOC_GEN_TS_PATH="/usr/local/lib/node_modules/ts-protoc-gen/bin/protoc-gen-ts"

protoc ${protofile} --proto_path . --plugin="protoc-gen-ts="${PROTOC_GEN_TS_PATH} --proto_path ${GOSRC}/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --grpc-web_out=import_style=typescript,mode=grpcwebtext:.
```

Everything is generated correctly but I have the mentioned issue at runtime:

> ERROR in /Users/USERXX/PathToProject/my-app/src/app/stub/Chat-apiServiceClientPb.ts

> ./app/stub/Chat-apiServiceClientPb.ts
[tsl] 

> ERROR in /Users/USERXX/PathToProject/my-app/src/app/stub/Chat-apiServiceClientPb.ts(12,44)

> TS2307: Cannot find module './google/api/annotations_pb'.

**Comment by Emixam23** [comment]
Hey!

As update:

`Just remove the imports related to google/api/annotations_pb, they are useless and don't cause (as for now) any issues while using gRPC`

**Comment by gmolau** [comment]
Can this be opened again? Removing the imports manually is not really a solution, is it?

**Comment by Jean-Dum** [comment]
I still have the exact same issue, and removing the import is not a solution for me
