### ISSUE TITLE
_pb.d.ts: Tried to write the same file twice

### ISSUE THREAD

**Issue by skuchuk** [improbable-eng/ts-protoc-gen#204]
**Versions of relevant software used**
Ubuntu 18.04.1 LTS
node: 8.12.0
npm: 6.4.1
ts-protoc-gen: 0.11.0
libprotoc 3.0.0

**What happened**
**_tried to create the gRPC client stub by running this bash script_**
PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/protoc-gen-ts-plugin"
OUT_DIR="./generated"

protoc \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --plugin="protoc-gen-grpc=${PROTOC_GEN_GRPC_PATH}" \
    --js_out="import_style=commonjs,binary:${OUT_DIR}" \
    --ts_out="service=grpc-node:${OUT_DIR}" \
    --grpc_out="${OUT_DIR}" \
    test.proto

**_On this proto file_**
syntax = "proto3";

service EnrichmentService {
    rpc Register (RegisterRequest) returns (RegisterResponse) {}
}

message RegisterRequest {
    string clientId = 1;
    string lock = 2;
  }
  
  message RegisterResponse {
    string clientId = 1;
    string status = 2;
    string session = 3;
    string message = 4;
  }

**_And got this error as a result_**
test_pb.d.ts: Tried to write the same file twice.

**What you expected to happen**
Client stub generated in a new folder called generated (tried this when folder doesn't exist and when I generate it, same result on both cases)

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by jonny-improbable** [comment]
ping @esilkensen as this appears to be a clash between the `protoc-gen-grpc` plugin and `protoc-gen-ts` when running with `service=grpc-node`.

**Comment by esilkensen** [comment]
I tried adding this proto file as a test case for ts-protoc-gen and wasn't able to reproduce the error - it generated test_pb.js, test_pb.d.ts, test_grpc_pb.d.ts, and test_grpc_pb.js with `service=grpc-node`.

@skuchuk, I wonder about `libprotoc 3.0.0` and if that corresponds to [this release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.0) from 3+ years ago? Is it possible you could try with a newer version of libprotoc to see if you get the same error?

**Comment by esilkensen** [comment]
Hm, though I also just tried modifying generate.js to use `const protocVersion = "3.0.0";` and that didn't raise an error either.

**Comment by esilkensen** [comment]
I tried adding this proto to the ts-protoc-gen test cases and it didn't raise any errors.

@skuchuk, I wonder if the issue is your
```
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/protoc-gen-ts-plugin"
```
This should point at a gRPC Node protoc plugin.

For example, if you install [`grpc-tools`](https://github.com/grpc/grpc-node#grpc-tools) it could be
```
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/grpc_tools_node_protoc_plugin"
```

**Comment by skuchuk** [comment]
@esilkensen 
Thanks!
My mistake was not using gRPC Node protoc plugin
Once I installed grpc-tools and set this properly to
PROTOC_GEN_GRPC_PATH="./node_modules/.bin/grpc_tools_node_protoc_plugin

The code was generated successfully
Thanks again

**Comment by jonnyreeves** [comment]
Thanks for helping to resolve this environment issue, @esilkensen.
Hopefully this issue will help signpost others who receive the same error
message in future.
