### ISSUE TITLE
non utf-8 characters in final output file?

### ISSUE THREAD

**Issue by srsudar** [improbable-eng/ts-protoc-gen#209]
I am new to JS protobufs and new to typescript. Apologies in advance of this is not the right place for this question.

I have what I think is a pretty simple `.proto` file defining a few messages. I am hoping to use the output in a Chrome extension, but the final JS file seems to include some non utf-8 characters that Chrome won't allow. Looking through the final file (which has been webpack'd as well), there are way more closure imports than I would have expected. I've pulled out some of the offending sections below.

Is this par for the course in JS protobufs, or am I inadvertently including more imports than I need? I'd love to use a pared down version without internationalization, eg, if that was possible.

`file` claims that it is indeed utf-8-encoded, so I am pretty thoroughly confused. Any pointers?

Here are some of what I think might are the non-utf-8 characters, assuming that my `vim` search is doing what I think it is:

```
goog.i18n.bidi.Format={LRE:"‪",RLE:"‫",PDF:"‬",LRM:"‎",RLM:"‏"},
goog.i18n.bidi.Dir={LTR:1,RTL:-1,NEUTRAL:0},
goog.i18n.bidi.RIGHT="right",goog.i18n.bidi.LEFT="left",
goog.i18n.bidi.I18N_RIGHT=goog.i18n.bidi.IS_RTL?goog.i18n.bidi.LEFT:goog.i18n.bidi.RIGHT,
goog.i18n.bidi.I18N_LEFT=goog.i18n.bidi.IS_RTL?goog.i18n.bidi.RIGHT:goog.i18n.bidi.LEFT,
goog.i18n.bidi.toDir=function(e,t){return"number"==typeof e?0<e?goog.i18n.bidi.Dir.LTR:0>e?goog.i18n.bidi.Dir.RTL:t?null:goog.i18n.bidi.Dir.NEUTRAL:null==e?null:e?goog.i18n.bidi.Dir.RTL:goog.i18n.bidi.Dir.LTR},
goog.i18n.bidi.ltrChars_="A-Za-zÀ-ÖØ-öø-ʸ̀-֐ऀ-῿‎Ⰰ-\ud801\ud804-\ud839\ud83c-\udbff豈-﬜︀-﹯﻽-￿",
goog.i18n.bidi.rtlChars_="֑-ۯۺ-ࣿ‏\ud802-\ud803\ud83a-\ud83bיִ-﷿ﹰ-ﻼ",
goog.i18n.bidi.htmlSkipReg_=/<[^>]*>|&[^;]+;/g,goog.i18n.
```

And here is the command I'm using to generate the annotations:

```
# Path to this plugin 
PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"

# Directory to write generated code to (.js and .d.ts files) 
OUT_DIR="./src/generated"

protoc \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" \
    --js_out="import_style=commonjs,binary:${OUT_DIR}" \
    --ts_out="${OUT_DIR}" \
    --proto_path="../proto/" \
    ../proto/annotations.proto
```

**Comment by srsudar** [comment]
It also adds about 1MB. Does that sound in the right ballpark?

**Comment by jonnyreeves** [comment]
Hey Sam, could you please create a full repro in a GitHub repo?

Thanks

**Comment by srsudar** [comment]
Sure thing, here it is:

https://github.com/srsudar/Chrome-Extension-with-React-and-Typescript-Starter-Pack

As I explain there, try to load `dist/` as an unpacked extension at `chrome://extensions`. It will complain that `contentscript.js` is not utf-8 encoded.

This problem appears after adding a proto that is built and output as typescript. `npm install && npm run build` should be sufficient to build yourself, with the relevant code in `src/contentscript/`.

Thanks for the help, and of course please don't hesitate to let me know I'm doing something foolish. My project skeleton comes from the the forked repo. I am also new to webpack, and I can't claim to understand everything going on with that build. If it is adding a step that somehow changes the encoding, I wasn't able to see what it was, and it only occurs after adding the proto.

**Comment by lugehorsam** [comment]
I am also having this issue. It prevents me from running tests on generated protobuf code from within Pupeteer.
