### ISSUE TITLE
Generate both grpc-node and grpc-web simultaneously

### ISSUE THREAD

**Issue by Multiply** [improbable-eng/ts-protoc-gen#211]
Would it make sense to be able to generate both grpc-node and grpc-web services at the same time, rather than the current if/else we have today?

**Comment by jonnyreeves** [comment]
Do you have this use case?

**Comment by Multiply** [comment]
I would like to use the service interface from grpc-node to build the GRPC Server, and would like to use the client from grpc-node to implement server-side clients.

And in turn use grpc-web client to implement clients that run in the browser.

Alternatively, I would like to optionally generate either the base d.ts files, or one of the services, to only generate a single set of files in one protoc call, or all of them in one go.

**Comment by jonnyreeves** [comment]
That makes sense.

Do you have thoughts on how this could work from a user perspective?

**Comment by Multiply** [comment]
**Scenario 1: Generate everything in one call**
Change the `service` parameter to allow comma separated values: https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/index.ts#L30-L31
Change the `else if` to an `if`: https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/index.ts#L49-L55

**Scenario 2: Generate only one set of files per call**
Add another parameter `generate` (or some other meaningful name that is not `service`), and allow comma separated values like in the proposal above.
Add an if around the base typescript files: https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/index.ts#L44-L47
When `generate` parameter contains `base`, output the base typescript files we just added an if around.
When `generate` parameter contains `grpc-web`, output the service web typescript files.
When `generate` parameter contains `grpc-node`, output the service node typescript files.

---

The latter proposal can be backwards compatible, and will support both scenarios. All in one go, or one set of files at a time.

**Comment by jonnyreeves** [comment]
Awesome, thank you for articulating these so clearly :)

Do you have a preference for either option? My personal preference would be
for the first option, but I'm open to persuasion.

> The latter proposal can be backwards compatible, and will support both
scenarios. All in one go, or one set of files at a time.

Do you think that Option 1 is not backwards compatible?

**Comment by Multiply** [comment]
Scenario 1 is definitely backwards compatible, but it does not allow you to skip the generation of the base fileset. So if I were to run two protoc on the same directory, one for grpc-web, and one for grpc-node, it would cause the base typescript files to be generated twice, unless we go for an approach like Scenario 2

**Comment by jonnyreeves** [comment]
Hey Jens,

> Scenario 1 is definitely backwards compatible, but it does not allow you
to skip the generation of the base fileset. So if I were to run two protoc
on the same directory, one for grpc-web, and one for grpc-node, it would
cause the base typescript files to be generated twice,

But if you are able to specify multiple 'service' outputs (ie:
`service=grpc-web,grpc-node') then there would be no need to run protoc
twice? Am I missing something?

**Comment by Multiply** [comment]
@jonnyreeves that's correct.

The 'need' for Scenario 2 stems from https://github.com/Dig-Doug/rules_typescript_proto/issues/10#issuecomment-550334084 where I'd like to avoid generating the base ts files twice.

I can work around it, though. Was just simple to implement (in a backwards-compatible way) now that I'm already look at implementing one of the scenarios above.

Let me know what you think, and I can try to submit a PR tomorrow.

**Comment by jonnyreeves** [comment]
Ah great, thanks for sharing.

PRs welcome, happy for you to take the lead on the design. Let me know if I
can help 👍

**Comment by Multiply** [comment]
@jonnyreeves I ended up going with scenario 2. I've made a WIP PR here: https://github.com/improbable-eng/ts-protoc-gen/pull/212

Please let me know of any changes or missing steps I need to complete, for it to be in a mergeable state.
