### ISSUE TITLE
Support for options / deadline

### ISSUE THREAD

**Issue by sjkummer** [improbable-eng/ts-protoc-gen#213]
Hi there, 

As far as I can see, the generated methods have an overload to pass a MetaData parameter - but no overload to pass an options parameter - e.g. to set a deadline for the method call.

It would be great to have a deadline / timeout to achieve better user experience in bad network environments.

Is such a thing planned? :-)

**Comment by jonnyreeves** [comment]
This would be a very welcome feature addition. Would you be interested in
helping to design and or implement?

**Comment by sjkummer** [comment]
Thanks for your quick response. Great to know that such a PR would be welcome. I'll have a dive into the code to see if I can easily contribute / implement this feature.
