### ISSUE TITLE
How to call static method deserializeBinary in factory function without type errors?

### ISSUE THREAD

**Issue by anselanza** [improbable-eng/ts-protoc-gen#214]
I am using `ts-protoc-gen` in  project where I have a number of messages that I'd like to be able to deserialise in a fairly generic way. So I have a factory function written in TypeScript that uses generics to do the job. The function below WORKS but I don't understand why I need to ignore the TS compiler in order to work properly!

```
/*
  Message deserialisers are generic. Provide the MessageClass and type detection handled accordingly.
  See https://www.typescriptlang.org/docs/handbook/generics.html for more
*/

export const decode = <T extends Message, K> (content: Uint8Array, messageClass: { new(): T }): K => {
  const m = new messageClass();

  /* TODO:
    m.constructor().deserializeBinary(content)
    passes TS compiler but m.constructor() is undefined at runtime

    m.constructor.deserializeBinary(content)
    TS compiler complains (silenced with @ts-ignore) but works as expected
  */
  //@ts-ignore
  const data = m.constructor.deserializeBinary(content);
  return data.toObject();
}
```

The above function will perform as expected when called, for example:
```
const payload: AgentRequestConfig.AsObject = decode(content, AgentRequestConfig);
```
(Here `payload` is indeed assigned the valid result as expected, an object of type `AgentRequestConfig.AsObject`. In my case `AgentRequestConfig` is a message class generated by `ts-protoc-gen` from a proto file.

If I understand correctly, `deserializeBinary` is a static function of the message class. So, normally I would be just fine writing the following:
```
  const d2 = AgentRequestConfig.deserializeBinary(content);
// no TS compiler errors, no runtime issues
```
But in my use case (the factory function) I need to call the static function on a given class of type `T`, so I use the "class dot constructor" mechanism to get hold of it. Which works, but, as I said, TS complains. Why?

**Comment by GeTOUO** [comment]
我建议你可以修改一下你的工厂函数签名:

```
decode = <T extends Message>(content: Uint8Array, messageClass: { new(): T; deserializeBinary(bytes: Uint8Array): T }): T
```
要求传入的解码类必须是符合类静态域中具有deserializeBinary函数的类型；当然还可以更简化一些:
```
decode = <T extends Message>(content: Uint8Array, messageClass: { deserializeBinary(bytes: Uint8Array): T }): T
```

因此你的实现可以是:
```
decode = <T extends Message>(content: Uint8Array, messageClass: { deserializeBinary(bytes: Uint8Array): T }): T {
    return messageClass.deserializeBinary(content);
}
```

**Comment by anselanza** [comment]
I'm afraid I don't understand the comments in between, but I assume you are recommending I change the function to something like:
```
public decode = <K extends Message>(
    content: Uint8Array,
    messageClass: { deserializeBinary(bytes: Uint8Array): K }
  ): K => messageClass.deserializeBinary(content);
```
It does indeed pass the TS compiler. I'm going to test a little and try to understand the syntax precisely.

Thanks for you help!

**Comment by anselanza** [comment]
OK, the recommended solution "works", but only if I am going to pass the mesageClass to this function as a parameter.

That is something I definitely do not want to have to do, since I have a class which already has an instance of messageClass (`this.messageClass` is of type `T` which in turn is of type `T extends Message`).

The closest I got was  
```
public decode = (content: Uint8Array): T => {
    const m: T = Message.deserializeBinary(content);
    return m;
  };
```
But this still produced a compiler error:

![constructor-error-crop](https://user-images.githubusercontent.com/3015222/70048733-4cd82700-15cb-11ea-949a-db3838c0e2a3.png)

**Comment by anselanza** [comment]
For now, I seem to have solved it like this:
```
export interface MessageConstructor<T extends Message> {
  new (): T;
  deserializeBinary(content: Uint8Array): T;
}

export default class Plug<T extends Message> {

///..... class implementation ..... 


  public decode = (content: Uint8Array): T => {
    const m = (this.messageCoder.constructor as MessageConstructor<
      T
    >).deserializeBinary(content);
    return m as T;
  };
```
