### ISSUE TITLE
Breaking enum map change with TS 3.7.x Upgrade

### ISSUE THREAD

**Issue by jaitthomas** [improbable-eng/ts-protoc-gen#215]
After upgrading to newest version of typescript 3.7.3, found the ts files are generated incorrectly and won't compile. Whenever the enum is referenced as below, the generated typescript can't find the corresponding enum.

`File1.proto`
`message GetResponse {`

**The below line fails during ts generation.**
`    map<string, EnumMessage.Status> status = 1;` 
`}`

`File2.proto`
`message EnumMessage{`
`enum Status {`
` ACTIVE = 1;`
` INACTIVE = 0;`
`}`
`Status status = 1;`
`}`

Generated output in *.d.ts looks like this.
`export type AsObject = {`
`    status: EnumMessage.Status[keyof EnumMessage.Status],` **it can't find the Status. What exist in ts 3.7.x is StatusMap, instead of Status.**
`  }`

**Workaround:**
Move the entry to same file. In this case EnumMessage should be moved from file2.proto to file1.proto

**Versions:**
typescript:3.7.3
ts-protoc-gen: "0.12.0",

**Comment by pelhage** [comment]
I think I'm facing a somewhat similar issue, where the generated types return the enum's index (0, 1, 2) as opposed to the key ('ENUM_KEY_ONE' 'ENUM_KEY_TWO')

**Comment by pelhage** [comment]
@jaitthomas curious to hear what workarounds you took here

**Comment by tonyneel923** [comment]
> @jaitthomas curious to hear what workarounds you took here

Did you ever find the answer to this issue?

**Comment by ts-jait** [comment]
Yes,  access with the Enum map, like EnumMessageMap[keyof EnumMessageMap]
