### ISSUE TITLE
Generated setter declarations have incorrect return type

### ISSUE THREAD

**Issue by scisci** [improbable-eng/ts-protoc-gen#218]
**Versions of relevant software used**

0.12.0

**What happened**

The generated return value for setters is void, but protoc actually returns this so you can chain your setters.
```
export class Thing extends jspb.Message {
  getId(): string;
  setId(value: string): void;
}
```
**What you expected to happen**
```
export class Thing extends jspb.Message {
  getId(): string;
  setId(value: string): this;
}
```
**How to reproduce it (as minimally and precisely as possible)**:

Should behave the same for all messages.

**Comment by Multiply** [comment]
@scisci did you end up fixing this yourself? We're in the same situation after updating grpc-tools, and would be interested in either contributing a fix, or help getting something going.

**Comment by scisci** [comment]
@Multiply, no I haven't had time to fix it. This repo seemed rather inactive last I checked though so  I have a general note of possibly switching to this library: https://github.com/thesayyn/protoc-gen-ts but haven't finished researching.

**Comment by Multiply** [comment]
@scisci I ended up maintaining our own fork as well. It was a rather simple change, luckily.
