### ISSUE TITLE
Generate Server bindings for grpc-node

### ISSUE THREAD

**Issue by Legogris** [improbable-eng/ts-protoc-gen#220]
It's possible that I am missing something, but it seems like the generated services only offer type checking for clients, not for servers.

It would be great if server implementations were also type-checked.

**Comment by yukio808** [comment]
I have an example of this working that I will submit a pull request for. From the example will generate something like this:
```typescript
interface IOrphanServiceServer {
  doUnary: grpc.handleUnaryCall<proto_orphan_pb.OrphanUnaryRequest, proto_orphan_pb.OrphanMessage>;
  doStream: grpc.handleUnaryCall<proto_orphan_pb.OrphanStreamRequest, proto_orphan_pb.OrphanMessage>;
}
```

This is something that I need/*want* as well.
