### ISSUE TITLE
Question: Why is map represented as Array in the object representation of a message?

### ISSUE THREAD

**Issue by SebastianStehle** [improbable-eng/ts-protoc-gen#229]
I think the title aready explains it.

I have a simpe message:

```
message UserDto {
    // Statistics counters.
    map<string, int64> counters = 8;
}
```

And the AsObject representation is:

```
export namespace UserDto {
  export type AsObject = {
    countersMap: Array<[string, number]>,
  }
}
```

What I don't understand:

* What the `Map` suffix?
* Why is represented as an array? I understand that it is closer to the wire format, but it would be easier to work with if it would be a simple Object when string keys are used.

e.g.
```
counters: { [key: string]: number };
```

**Comment by Raiondesu** [comment]
Absolutely valid complaint here. This goes against all semantic **and** sanity norms.

**Comment by jonnyreeves** [comment]
Agreed, however ts-protoc-gen supplies the typings for the google grpc
library so it's not an issue we can resolve (unless I've missed something?)
:(
