### ISSUE TITLE
Confusing behavior of passing a string into generated function for bytes property

### ISSUE THREAD

**Issue by rodly** [improbable-eng/ts-protoc-gen#230]
I noticed that the generated function signature for a proto schema property of type bytes is `Uint8Array | string`. I noticed that when passing in a string that contains non-base64 values that upon serializing the object that those non-base64 values are lost and replaced with "valid" ones. This might be an expected behavior of protobufs but I do think it's misleading to provide a function that accepts a `string` but has this nasty side-effect. I'm curious if this has come up in prior discussions and whether there were any proposed solutions (throw exception on non-base64 char values, provide base64 encode/decode functionality in the generated code, etc)?

**Comment by yagop** [comment]
I'm facing the same `Uint8Array | string` problem
