### ISSUE TITLE
Support for proto3 optional fields

### ISSUE THREAD

**Issue by stof** [improbable-eng/ts-protoc-gen#263]
This is resurrecting https://github.com/improbable-eng/ts-protoc-gen/issues/227 which has been closed without any feedback.

protoc 3.12+ has experimental support for `optional` in proto3 (see https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md). Of all the code generators I checks, this one is the only one which does not support it.
As its goal is to generate declaration files for the protoc JS output which does support that feature, it would be great if it could be supported.

**Comment by stof** [comment]
Looking at the code, I think that supporting that could be as easy as updating the implementation of `hasFieldPresence` in https://github.com/improbable-eng/ts-protoc-gen/blob/e680d6948ecf2ea208b07e8844317abc43a69702/src/ts/message.ts#L17 to check for the new option (and marking the feature as supported in the CodeGeneratorResponse of course).

**Comment by sky-lake** [comment]
This would be a very useful feature for users who are holding on to proto2 because of `optional` support.

**Comment by huan** [comment]
I definitely need this feature. Now it's a blocker in my project https://github.com/wechaty/grpc/issues/109

**Comment by awbraunstein** [comment]
I'm going to take on fixing this. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52380 is a requirement to fix this in this repo.

**Comment by MarcusLongmuir** [comment]
Thanks for picking this up @awbraunstein. Apologies for the delay on acking this. 

I made progress on [this branch](https://github.com/improbable-eng/ts-protoc-gen/tree/proto3-optional), but got sidetracked before getting to address the types that you've contributed to DefinitelyTyped.

Feel free to take from that branch (if you don't already have it functioning) and raise a PR once the types are merged. Thanks!

**Comment by awbraunstein** [comment]
@MarcusLongmuir  Thanks for the pointer to the branch. I have something that looks very similar locally, though I haven't written any tests yet, so I may steal yours.
