### ISSUE TITLE
Add type definitions for grpc_out generate_package_definition option

### ISSUE THREAD

**Issue by pkwarren** [improbable-eng/ts-protoc-gen#266]
Currently, the typescript definitions don't match the generated code from grpc-tools if you are using the `generate_package_definition` option to `--grpc_out`. In this case, the export is the full name of the gRPC package and there is no client export: https://github.com/grpc/grpc-node/blob/17b43dfbfd24f1e3daa7b7ad2c0b757f77b769a0/packages/grpc-tools/src/node_generator.cc#L204-L208

**Versions of relevant software used**
0.14.0

**What happened**
When using `--grpc_out=generate_package_definition` (https://github.com/grpc/grpc-node/tree/master/packages/grpc-tools#usage), the type definitions exported by ts-protoc-gen don't match the generated code from grpc-tools.

**What you expected to happen**
The type definitions to match the output from grpc-tools.

**How to reproduce it (as minimally and precisely as possible)**:
Generate protobuf code w/ `grpc_tools_node_protoc ... --grpc_out=generate_package_definition:out --ts_out=service=grpc-node,mode=grpc-js:out`

**Comment by samlevin** [comment]
Just ran into this as well. How'd you work around it? @pkwarren

**Comment by pkwarren** [comment]
@samlevin - We just stopped using the option and use `grpc_out=grpc_js` instead.
