### ISSUE TITLE
Interfaces are created for proto enumerations

### ISSUE THREAD

**Issue by Alex66955** [improbable-eng/ts-protoc-gen#268]
**ts-protoc-gen: 0.14.0**
**libprotoc: 3.15.6**

**What happened**
Updating module to the last version causes creation of interfaces instead of enumerations
Proto:
```
enum scaleIdx {
    SCALE_DISPLAYED = 0;
    SCALE_1 = 1;
    SCALE_2 = 2;
    SCALE_COMPOUND = 3;
}
```
d.ts:
```
export interface scaleIdxMap {
  SCALE_DISPLAYED: 0;
  SCALE_1: 1;
  SCALE_2: 2;
  SCALE_COMPOUND: 3;
}

export const scaleIdx: scaleIdxMap;
```

**What you expected to happen**
d.ts:
```
export enum scaleIdx {
  SCALE_DISPLAYED = 0,
  SCALE_1 = 1,
  SCALE_2 = 2,
  SCALE_COMPOUND = 3,
}
```

**Full logs to relevant components**
Executed command:
`protoc --plugin=protoc-gen-ts=node_modules/.bin/protoc-gen-ts --ts_out=generated     --proto_path=protos --proto_path=shared/protos protos/*.proto shared/protos/*.proto shared/protos/generated/*.proto`

**Comment by thesayyn** [comment]
I would recommend a plugin that we have been developing and maintaining for these edge cases which is caused by protocol buffers javascript output itself.

https://github.com/thesayyn/protoc-gen-ts

**Comment by AJLoveChina** [comment]
I am facing the same issue. I really need protoc enum to be compiled as `enum`, not interface..

**Comment by thesayyn** [comment]
@AJLoveChina you can check out the alternative.

**Comment by Alex66955** [comment]
I also solved my issue with that plugin.
