### ISSUE TITLE
Can this be used to generate grpc service definitions?

### ISSUE THREAD

**Issue by danbopes** [improbable-eng/ts-protoc-gen#27]
In the [grpc node examples folder](https://github.com/grpc/grpc/blob/master/examples/node/static_codegen/README.md) they generate the contracts between the services, but also the service itself [_grpc_pb.js](https://github.com/grpc/grpc/blob/master/examples/node/static_codegen/helloworld_grpc_pb.js). I notice that you can add service=true to generate the grpc-web bindings, but what about the grpc service definitions?

**Comment by MarcusLongmuir** [comment]
@danbopes: This project (ts-protoc-gen) currently only generates the method definitions in a format that https://github.com/improbable-eng/grpc-web requires. 

I think it might make sense to generate the node grpc declarations in a separate plugin - I realise by the same logic the grpc-web definitions should also be generated by a separate plugin, but there hasn't been a pressing need to.

To that end, creating a TypeScript library that can be used to build these various protoc plugins would be a good next step.

This could be done by splitting the parsing and printing steps that this plugin performs and creating an interface that can be used to print other formats.

**Comment by jonny-improbable** [comment]
See #42

**Comment by jonahbron** [comment]
@danbopes This is now available in version 0.6.0, this issue can be closed.
