### ISSUE TITLE
Switch to github.com/dcodeIO/ProtoBuf.js?

### ISSUE THREAD

**Issue by mackross** [improbable-eng/ts-protoc-gen#28]
This library has maintained TS support which would allow ts-protoc-gen to be slimmed down. Further because we're using static protobuf the minimal dependency is only 6.5k.

**Comment by gedw99** [comment]
How big is the output from this lib though ?

Also is it able to use grpc-web and websockets ?

**Comment by mackross** [comment]
Websockets or grpc-web shouldn't have an impact as this doesn't make any assumptions about the transport layer (gRPC & gRPC web separate deserialization from transport) e.g. grpcweb+json or grpc+flatbuffers are perfectly valid. My expectation would be that a static compiled serializer would be the same or smaller than a dynamic one.

**Comment by metled** [comment]
I guess it's possible but need some changes. since grpc-web transport layer used [some google-protobuf Message interface functions](https://github.com/improbable-eng/grpc-web/blob/master/ts/src/message.ts), i.e. deserializeBinary() serializeBinary(), which should be changed to encode() decode() of dcodeIO/ProtoBuf.js

**Comment by gedw99** [comment]
this is way better IMHO

https://github.com/improbable-eng/grpc-web

**Comment by easyCZ** [comment]
For now, I believe that it is beneficial for the community to have the option of using either `Protobuf.js` on it's own or going with `ts-protoc-gen`. I think we should not be implementing protobuf js as a build target at this point.

I'm gonna close this for now. If you have a good usecase, please do let us know.

**Comment by fatfatson** [comment]
I think `dcodeIO/ProtoBuf.js` is more js-like than google's,
such as creating a message directly from a js object, without invoking a lot of `setXXXX`
so, it's good to have an option for generating target, I'll choose dcodeIO's first.
