### ISSUE TITLE
Generate stubs for making grpc calls more convenient

### ISSUE THREAD

**Issue by thakkarparth007** [improbable-eng/ts-protoc-gen#30]
Currently we've to use `grpc.unary` or `grpc.invoke` for making any kind of call. While that'd make sense to do if we've to handle headers and trailers for all calls, there are many situations where the rpc semantics are much simpler. Having stub methods to call will provide uniformity with the rpc interfaces exposed in other languages, and will also make development a bit more convenient.

I propose to have stub methods for unary-unary and unary-streaming calls, such that the stubs can be used with the nice async-await syntax including the for-await loop for unary-streaming calls.

**Comment by thakkarparth007** [comment]
I've made a rough PR for this #29. I use this code directly in my project, and so the PR is quite tied up to the project. However I'd be happy to generalize this a bit in order for it to be useful to the users of this library.

**Comment by jonahbron** [comment]
I would love to see this generalized and merged @thakkarparth007 , the current API is a bit of a pain.  It would be nice it closer matched the interface from the official grpc-web repository, as described in another comment of mine here:

https://github.com/improbable-eng/grpc-web/issues/135#issuecomment-369418340

**Comment by jonny-improbable** [comment]
Support for this just landed in 0.6.0
