### ISSUE TITLE
Having permission denied issue & unable to locate file 

### ISSUE THREAD

**Issue by solo-dancer** [improbable-eng/ts-protoc-gen#33]
**I tried this on ubuntu  :**

_solo@solo-Aspire-5740:~/WebstormProjects/GRPCCLient/GRPCTS$ ./protoc --plugin=protoc-gen-ts= ./node_modules/.bin/protoc-gen-ts --js_out=import_style=commonjs,binary:generated --ts_out=service=true:generated   -I ./proto ./proto/a.proto

./node_modules/.bin/protoc-gen-ts: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think)._

**If put them in the same folder location :** 

_solo@solo-Aspire-5740:~/WebstormProjects/GRPCCLient/GRPCTS$ ./protoc --plugin=protoc-gen-ts= ./protoc-gen-ts --js_out=import_style=commonjs,binary:generated --ts_out=service=true:generated   -I ./ ./a.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:546] No syntax specified for the proto file: protoc-gen-ts. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
protoc-gen-ts:1:1: Expected top-level statement (e.g. "message")._

**This is what i get on windows  : <Note : I am running CMD in admin mode >**

_C:\AltsLab\alts-grpc\GRPCClientNew\protoc.exe --plugin=protoc-gen-ts=C:\AltsLab\alts-grpc\GRPCClientNew\node_modules.bin\protoc-gen-ts --ts_out=service=true:generated C:\AltsLab\alts-grpc\GRPCClientNew\proto -I C:\AltsLab\alts-grpc\GRPCClientNew\proto C:\AltsLab\alts-grpc\GRPCClientNew\proto\a.proto

C:\AltsLab\alts-grpc\GRPCClientNew\proto: Permission denied_

Can you please help me resolve either one of this ?
Thanks!

**Comment by cristianmad** [comment]
I'm running into the exact same issue. Where you able to find the problem?
Thanks

**Comment by easyCZ** [comment]
Hi @solo-dancer, @cristianmad 

Would you be able to provide a small repository which reproduces this problem? Ideally it would include the proto files and the invocation you're making. This will help us investigate the issue and come up with solutions.

Thanks!

**Comment by jonny-improbable** [comment]
Closing as stale, please reopen with a repro case.
