### ISSUE TITLE
Chain builder to build Message

### ISSUE THREAD

**Issue by bianbian-org** [improbable-eng/ts-protoc-gen#43]
Besides this [more ergonomic client stubs](https://github.com/improbable-eng/grpc-web/issues/135#issuecomment-369418340), I suggest chain builder to build Message:
```javascript
service.Query(Request.newBuilder().setId(1).setName("xxx").build(), ...
```
like Java simple-rpc: https://grpc.io/docs/tutorials/basic/java.html#simple-rpc-1
Is it possible?

**Comment by jonny-improbable** [comment]
Not without changes to the underlying google/protobuf project to generate your suggested builder pattern; this library only generated Typescript Definition files (`.d.ts`) to provide typehints for protos (well and some service stubs as well :))

**Comment by rjmunhoz** [comment]
According to [this](https://github.com/protocolbuffers/protobuf/issues/6860#issuecomment-567230883), protobuf now supports chaining.
I'd love to have that implemented here.
