### ISSUE TITLE
Continously release current version as ts-protoc-gen@next

### ISSUE THREAD

**Issue by easyCZ** [improbable-eng/ts-protoc-gen#50]
In order to allow experimentation with new features earlier, we should continuously publish a snapshot of master. We can do this by publish it as a `ts-protoc-gen@next` version. This should run as part of CI on successful build.

**Comment by jonnyreeves** [comment]
OK, I've made some progress on this, however I am going around in circles and would appreciate some guidance :)

After following [this guide](https://docs.travis-ci.com/user/deployment/npm/), I've modified our `.travis.yml` to add a `deploy` step which successfully performs an `npm publish --tag=next` each time master builds.

This works great, however on successive builds of master the publish step fails with the following error:

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 0.7.0-pre. : ts-protoc-gen
```

I'm guessing I need to 'bump' the version in our package.version but I'm unsure how to do this; sure I cloud use something like [standard-version](https://github.com/conventional-changelog/standard-version) to achieve this, but won't this result in an inifinite loop each time I commit the bumped package version? 😕

**Comment by jonnyreeves** [comment]
Ah ok, I was just overthinking this. Taking inspiration from the [Typescript package](https://www.npmjs.com/package/typescript) I can setup a cronjob on Travis to run nightly and use the datestamp as a unique suffix on the package version.

**Comment by jonnyreeves** [comment]
Ok this is now done from a CI and release script level. Just need to update the README (and maybe the changelog) to mention that you can install prereleases using the @next tag

**Comment by jonnyreeves** [comment]
Done
