### ISSUE TITLE
Include documentation from protos

### ISSUE THREAD

**Issue by bhollis** [improbable-eng/ts-protoc-gen#58]
As a feature request, it would be nice if the generated TypeScript definitions included documentation strings copied over from comments in the original protos.

**Comment by jonnyreeves** [comment]
@bhollis This sounds like a great idea. I'm not overly familiar with the internals of protoc-gen; is anyone able to point me at the documentation for the javascript library which would allow me to programatically access the documentation present in the protos?

**Comment by easyCZ** [comment]
This should be possible by Retrieving through the source code info. An example is better for this:

```js
const descriptor: FileDescriptorProto = ...;
const sourceInfo: SourceCodeInfo = descriptor.getSourceCodeInfo();
const locations: Array<SourceCodeInfo.Location> = sourceInfo.getLocationList();

locations.forEach(location => location.getLeadingComments()) // or similar
```
Haven't tested this, however.

**Comment by easyCZ** [comment]
Digging deeper into this, we can base a lot of it on the proto definition itself.

https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L728

**Comment by easyCZ** [comment]
Made some progress. I can now reliably figure out how to map fields to their respective comments. The remainder of the work is to clean it up and make a bit sane.

The gist of the change is as follows:
```proto
package examplecom;

message Comments {
    // My_string field with a comment
    string my_string = 1;
    /// my_bool field with a tripple slash comment
    bool my_bool = 2;
    /* some_labels with a comment */
    repeated string some_labels = 3;
}
```
The corresponding `CodeGenerationRequest` can be converted to a map of fields to their respective locations, ie 
```
'examplecom/comments.proto.examplecom.Comments': '4,0',
'examplecom/comments.proto.examplecom.Comments.my_string': '4,0,2,0',
'examplecom/comments.proto.examplecom.Comments.my_bool': '4,0,2,1',
'examplecom/comments.proto.examplecom.Comments.some_labels': '4,0,2,2'
```

The numbers represent the following:
* `4` is an individual proto message
* `3` is a nested proto message
* `2` is a field inside a proto message
* there are more for enums and others

So, `'examplecom/comments.proto.examplecom.Comments': '4,0',`
4 => proto message
0 => the first proto proto descriptor in the `CodeGenerationRequest`

Similarly, `'examplecom/comments.proto.examplecom.Comments.my_bool': '4,0,2,1',`
4 => proto message
0 => the first proto proto descriptor in the `CodeGenerationRequest`
2 => a field of this proto message
1 => the second field

And for completeness, the proto generation request in JSON looks like 
```json
{
  "sourceCodeInfo": {
    "locationList": [
      {
        "pathList": [
          12
        ],
        "spanList": [
          3,
          0,
          18
        ],
        "leadingDetachedCommentsList": [
          " This is a top level comment\n spanning multiple lines. "
        ]
      },
      {
        "pathList": [
          4,
          0,
          2,
          0
        ],
        "spanList": [
          9,
          4,
          25
        ],
        "leadingComments": " My_string field with a comment\n",
        "leadingDetachedCommentsList": []
      },
      {
        "pathList": [
          4,
          0,
          2,
          1
        ],
        "spanList": [
          11,
          4,
          21
        ],
        "leadingComments": "/ my_bool field with a tripple slash comment\n",
        "leadingDetachedCommentsList": []
      }
    ]
  }
}
```

**Comment by thebigredgeek** [comment]
@easyCZ any updates here?  excited about this feature

**Comment by easyCZ** [comment]
Things got a bit more hectic and I wasn't able to work on this. Should be able to get back to it soon. I'll push my working branch and you're welcome to contribute!

The above outline of the problem should be sufficient to understand the problem. The tricky part is restructuring of the code to make it easy to extract the relevant parts of the comments at the right points in the generation pipeline.

**Comment by nothingrandom** [comment]
Hey @easyCZ. I can see this has been marked as as stale / closed. Is that actually the case, or do you plan to get this finished and integrated?

I'd really love this feature, it'd make it a lot easier for me to understand the generated files. I know it's not the same _but_, the java proto generator has comments in the right places. Maybe referencing that would help ensure the comments are in the correct points of the pipeline? (https://github.com/grpc/grpc-java/)

**Comment by easyCZ** [comment]
Hey @nothingrandom, definitely still want this to be done. Unfortunately, I've not had enough time to make any significant progress on this. If you'd like to pick up where I left off a PR would be appreciated. I've also bounced this issue around my colleagues who may be able to pick it up.
