### ISSUE TITLE
Camel-cased OneOf message typings are not generated correctly.

### ISSUE THREAD

**Issue by MHDante** [improbable-eng/ts-protoc-gen#63]
There's an issue with the TS generated for OneOfs that are camelcased. Both the Case Enum type and the Case enum accessor have the wrong casing. 

The following message:

```protobuf
message MyMessage{
    oneof thisIsAField{
        int32 anInt = 1;
        string theString = 2;
    }
}
```

This produces the following TS code:

```typescript
export namespace MyMessage {
  export type AsObject = {
    anint: number,
    thestring: string,
  }

  export enum ThisIsAFieldCase {
    THISISAFIELD_NOT_SET = 0,
    ANINT = 1,
    THESTRING = 2,
  }
}
```

And the following JS code:
```javascript
/**
 * @enum {number}
 */
proto.MyMessage.ThisisafieldCase = {
  THISISAFIELD_NOT_SET: 0,
  ANINT: 1,
  THESTRING: 2
};
```

As far as I can tell, there is a general bug with the way camelcase fields are handled in pbjs, but it sees like ts was always using the same bug (and was therefore compatible). This is not the case with OneOfs

As a workaround, you can either cast to Any, or you can use one word oneof fields.

**Comment by jonnyreeves** [comment]
Thanks for raising @MHDante, Please could you take a look at #67 and confirm this addresses the main issue here (the classname not matching).

If I understand correctly there is a secondary issue that the fieldNames in the `AsObject` representation also do no match.

**Comment by MHDante** [comment]
As far as I can tell, there is no secondary issue in the AsObject naming. (Other than protoc's inherent destruction of camel humps) 

#67 does in fact address this issue here. Thanks for your prompt attention.

**Comment by MHDante** [comment]
Out of curiosity, is there an issue regarding the loss of camelcasing in the JS compiler? The closest thing I found was: https://github.com/google/protobuf/issues/1591
