### ISSUE TITLE
Service stubs closing requests without headers

### ISSUE THREAD

**Issue by atecce** [improbable-eng/ts-protoc-gen#65]
Hai! 

I've generated a simple service stub and I'm attempting to test my client with a very simple script. In the `client.get` method, I'm getting the following stack trace.

<img width="824" alt="screen shot 2018-05-14 at 12 26 25 pm" src="https://user-images.githubusercontent.com/10567112/40010249-3053a6e0-5772-11e8-9cb9-d0755a2f93cf.png">

Is this a result of the request not being made from a browser? Is there an API I can hook into which lets me set HTTP headers manually?

**Comment by atecce** [comment]
ping

**Comment by atecce** [comment]
halp

**Comment by jonnyreeves** [comment]
Hey sorry for the delay, it's unlikely that anyone will be able to debug this unless you can provide a project which provides a minimal repro of your issue

> Is this a result of the request not being made from a browser? 
Interesting, what's your use-case? The Service Stubs generated by ts-protoc-gen are intended to use [grpc-web](https://github.com/improbable-eng/grpc-web) as the transport which typically expects a browser-based environment.

> Is there an API I can hook into which lets me set HTTP headers manually?
HTTP Headers? No. You can however specify custom gRPC metadata when making a request.

**Comment by atecce** [comment]
>Interesting, what's your use-case? The Service Stubs generated by ts-protoc-gen are intended to use grpc-web as the transport which typically expects a browser-based environment.

My ultimate use case is to integrate the client into an Excel Add-In powered by Vue and migrate . In the interim I wanted to simply test the client with a script that roughly looks like the following.

```typescript
import { TestClient } from "./generated/Test_pb_service"
import { Query } from "./generated/Test_pb"

const client = new TestClient("https://localhost:8080")
const query = new Query();

query.setMessage("test");

client.get(query, function(err, res) {
    if (err) {
        console.log(err)
    } else {
        console.log(res)
    }
})
```

Where `localhost:8080` is a `grpcwebproxy`.

If the answer is, "`grpc-web-client` doesn't support requests made outside of a browser", that's okay! Just wanted to verify that before trying to get grpc-web, Vue, Excel-Add-Ins and TypeScript to all play nice at once.

And no problem! Sorry for the hassle :D. I also just noticed that this would probably be a more fitting issue for `grpc-web-client`

**Comment by jonnyreeves** [comment]
> My ultimate use case is to integrate the client into an Excel Add-In powered by Vue

That *is* an unorthodox use-case! :)

> this would probably be a more fitting issue for grpc-web-client

Agreed, this is almost certainly an issue with the transport rather than the generation of the service stubs. Personally, I would suggest adding some debugging to the grpcwebproxy instance that you have running so you can see what metadata is making it from the client (Excel) - it's possible that Excel is stripping some/all HTTP headers - although that's pure speculation at this point.

> Sorry for the hassle :D

No hassle at all - good luck with your project :)
