### ISSUE TITLE
Support client-side and bidi streaming in grpc-web Service Stubs

### ISSUE THREAD

**Issue by pjm17971** [improbable-eng/ts-protoc-gen#66]
I'm trying to use this library on node.js to talk to a gRPC server. In my proto file I have 
```
rpc WatchMetric(stream MetricSubscriptionRequest) returns (stream Event) {}
```

However, this results in the following code being generated:

*example_pb_service.js*
```
Watcher.prototype.watchMetric = function watchMetric() {
  throw new Error("Client streaming is not currently supported");
}
```

*example_pb_service.d.ts*
```
watchMetric(): void;
```

Since v0.6.0, grpc-web provides an experimental websocket transport which should allow client-side and bidi streaming.

**Comment by jonnyreeves** [comment]
Thanks for raising @pjm17971 and sorry to hear you are encountering difficulties. It's very possible that we have a gap in our test-coverage here - would you be in a position to create a repro case (preferably as a test)?

Thanks.

**Comment by pjm17971** [comment]
This is a little different from the actual code we're trying to write, but here's an example:
https://github.com/esnet/test-grpc-streaming

The watchMetric() rpc is here, and shows the problem:
https://github.com/esnet/test-grpc-streaming/blob/master/example_pb_service.d.ts#L36

There's a build script build_protos.sh that has the command I used to build those. Hopefully this is enough to have a look at it.

Thanks!

**Comment by jonnyreeves** [comment]
Hi @pjm17971 , sorry for the delay in getting back to you and thank you for creating such a thorough repro case for me.

So if you look at the [generated javascript for the service](https://github.com/esnet/test-grpc-streaming/blob/master/example_pb_service.js#L30) you will see the root cause of the error:

```
Watcher.prototype.watchMetric = function watchMetric() {
  throw new Error("Client streaming is not currently supported");
}
```

This is a throw back to a previous version of grpc-web which didn't provide support for client-side streaming; support was added in grpc-web@0.6.0 via the websocket transport.

ts-protoc-gen needs to be updated to provide support for this new functionality; I will convert your issue's title and summary to reflect that.

Thanks, and sorry for the inconvenience.

**Comment by jonnyreeves** [comment]
If I've read [the docs](https://grpc.io/grpc/node/grpc-ClientWritableStream.html) correctly then the API should closely resemble the `grpc-node` one and will look something like this:

* Client Side Streaming *
```
const client = doClientStream(...)
client.on('metadata', (metadata) => { /* handle metadata */ });
client.on('status', (status) => { /* handle grpc status when stream is closed */ });
client.write(/* some data */);
client.write(/* some data */);
client.end(); // complete sending data.
client.cancel(); // cancel the stream from the client.
```

* Bidirectional Streaming *
```
const client = doClientBidiStream(...)
client.on('data', (msg) => { /* hande incoming data */ });
client.on('metadata', (metadata) => { /* handle metadata */ });
client.on('status', (status) => { /* handle grpc status when stream is closed */ });
client.write(/* send some data */);
client.write(/* send some more data */);
client.end(); // close the stream
client.cancel(); // cancel the stream from the client.
```

Feedback welcome from those who have used the grpc-node API in anger, please!

**Comment by jared2501** [comment]
This API looks great to me! Would love to srr an implementation, or can try and send a PR in a few days.

**Comment by pjm17971** [comment]
Thanks for looking at this @jonnyreeves. I think this API looks good. Really looking forward to being able to use this.

**Comment by jonnyreeves** [comment]
Being worked in on #82

**Comment by jonny-improbable** [comment]
One thing to note is that with the above API ClientStreams open the connection to the server when the first message is sent, where-as BiDiStreams will open the connection to the server immediately - Please let me know if this is undesirable

**Comment by pjm17971** [comment]
Any progress on this one?
