### ISSUE TITLE
npm run-script build fails due to wrong types on dependency

### ISSUE THREAD

**Issue by Junkern** [improbable-eng/ts-protoc-gen#73]
I just picked up https://github.com/improbable-eng/ts-protoc-gen/pull/42/files , created a new branch on my fork and did `npm install` and after that a `npm run-script build`. It failed with

```
node_modules/@types/text-encoding/index.d.ts(52,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'TextDecoder' must be of type '{ new (label?: string | undefined, options?: TextDecoderOptions | undefined): TextDecoder; protot...', but here has type 'TextDecoderStatic'.
node_modules/@types/text-encoding/index.d.ts(54,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'TextEncoder' must be of type '{ new (): TextEncoder; prototype: TextEncoder; }', but here has type 'TextEncoderStatic'.
```

This dependency is only used in https://github.com/improbable-eng/ts-protoc-gen/blob/master/test/helpers/fakeGrpcTransport.ts#L20

This could be replaced by a `const bytes = new Buffer(asString);` tests still pass. Were there any special reasons why to use `TextEncoder` in the first place?

I would be happy to provide a PR for that.

**Comment by jonnyreeves** [comment]
Fixed by #74
