### ISSUE TITLE
Add ts-protoc-gen-library rule to generate protos using Bazel

### ISSUE THREAD

**Issue by easyCZ** [improbable-eng/ts-protoc-gen#77]
In order to improve support for Bazel, we should introduce a rule to allow generation of TS protos idiomatically with Bazel.

## The benefits
1. Ability to synchronise generated code for multiple targets
2. Native experience for Bazel users
3. Contribution to the ecosystem of Bazel

## How
A [ts_proto_library](https://github.com/bazelbuild/rules_typescript/pull/193) already exists [(docs](http://tsetse.info/api/protobufjs/ts_proto_library.html)) leverages Protobuf.JS. We can utilize the learnings from there to add a similar rule.
The code should be contributed to [rules_typescript](https://github.com/bazelbuild/rules_typescript) for uniformity but we should test against the rule ourselves on our CI.

## Notes
Initial research of this shows this should be very doable and can provide better integration with Bazel than Protobuf.JS as we can choose to compile individual protos based on the dependency analysis from Bazel.

If you have a use case for _ts-protoc-gen_ and _Bazel_, please let us know so we can better cater for it.

**Comment by easyCZ** [comment]
Current progress is on https://github.com/easyCZ/rules_typescript/tree/feature/ts-protoc-gen

**Comment by coltonmorris** [comment]
I've opened a pull request in this repo with the rule [here](https://github.com/improbable-eng/ts-protoc-gen/pull/84).
