### ISSUE TITLE
Inconsistent setField method in generated examples

### ISSUE THREAD

**Issue by MHDante** [improbable-eng/ts-protoc-gen#78]
A question about the `examples/generated` files. 

in #67, @jonnyreeves commited updated the generated files when commiting, resulting in the following change:

https://github.com/improbable-eng/ts-protoc-gen/pull/67/files#diff-6cee6eac2b0bae17197dc838b7af57a2L208

I'm trying to set up development on my local environment, and the most recent version of protoc (3.5.1) is generating js that uses the  `setProto3*Field` methods (e.g. `setProto3EnumField`)

I asume that perhaps @jonnyreeves'  protoc is out of date, or is there a way to generate the js file using the generic `setField` method?

**Comment by jonnyreeves** [comment]
Ah yes, sorry about that. I think we need to enforce a given version of protoc for consistency. Two options I see are:

1. Add a CI build step which regenerates the example protos and then checks for changes, if there are any it will fail the CI build with a descriptive error message

2. Add a local build step which checks the users locally installed version of or protoc.

However I'm welcome to other suggestions 😀

**Comment by MHDante** [comment]
2 seems to be a problem as protoc is usually installed globally. A server developed on the same machine may require a newer version. 

1 is nice, as it serves as a bit of a unit test against unwanted regressions, but I assume most changes to the code would cause output to differ, and CI tests that fail always are a bit annoying.

You could also add the version to Contributing.md and manually unwarranted changes to the generated output in PRs

**Comment by jonnyreeves** [comment]
Oh yes, both of these are flawed, probably not a great idea to respond to GitHub issues at 7am 😂

You're right, updating the contribution guide is an obvious first step, however another spin on option #2 may be to download protoc as part of generate.sh as it is a standalone binary

**Comment by easyCZ** [comment]
I'm leaning towards a pinned version of protoc for the repository. This makes the experience consistent for all contributors. Furthermore, an upgrade is only a PR away which helps us track the _protoc_ target we're building against.

I can see two ways to get this done:
1. Docker container with `protoc`
2. Use [grpc-tools](https://www.npmjs.com/package/grpc-tools?activeTab=versions) which bundles `protoc` but hasn't been updated in a while
3. Use Bazel to generate the examples. This would require contributors to install _bazel_.

I like 1 and 3.
