### ISSUE TITLE
Developing ts-protoc-gen on windows

### ISSUE THREAD

**Issue by MHDante** [improbable-eng/ts-protoc-gen#79]
The use of sh files, and especially calling the protoc-gen-ts  (uses `#!/usr/bin/env node` to execute), from generate.sh makes it really hard to run the scripts on windows. (e.g. `generate.bat`). Even when running Cygwin or msys

I've messed around with making cmd proxies and whatnot, as well as detecting the system on windows manually in the sh file, but i'd rather ask: Is building on windows going to be supported?

If not, that's ok. I've spent the evening installing Windows Subsystem for Linux and that seems to have done it. The readme could clarify that this is the way to go.

If yes, what's the approach you'd like to take in order to allow running scripts on windows?
I see three options, but there may be more available:
- Maintain sh scripts that run on windows, and insist that users have bash installed
- Maintain powershell (or cmd) scripts that run on windows.
- use js scripts that run from node to do the work

Once you decide, I'd be happy to make a pr.

**Comment by jonnyreeves** [comment]
Hey, sorry as you can probably guess I'm not a Windows user 😂

I think having a Windows build would make it easier for others to contribute to the project so would be in favour.

Personally I'd be in favour of your third suggestion, replacing the shell scripts with node scripts as this way we are less likely to regress a build system in future

**Comment by easyCZ** [comment]
Thanks for raising this!
I think a _js_ solution is appropriate here. Let us know if you'd like any help!

**Comment by jonnyreeves** [comment]
I've got a local branch where I'm working on a replacement to `generate.sh` with a NodeJS script.

**Comment by akrone-hach** [comment]
Just curious. Is this dead?

**Comment by jonny-improbable** [comment]
It would appear that all bash scripts and use of linux commands were "fixed" by @esilkensen in #193. I'm going to resolve this issue now - please open a new one if there are any outstanding blockers to developing within a Windows environment.
