### ISSUE TITLE
Imported File With Extension

### ISSUE THREAD

**Issue by graywolf336** [improbable-eng/ts-protoc-gen#8]
I have a `bookService.proto` file which imports `books.proto` and when the JavaScript is generated for `bookService.proto` it contains `var books_pb = require('./books_pb.js');`. The addition of the extension is throwing errors in my build.

Only guess after going through the code I can find is https://github.com/improbable-eng/ts-protoc-gen/blob/master/src/js/fileDescriptorJSServices.ts#L30 where it places the depencies at and replaces `.proto` with `_pb` but doesn't take off the JavaScript extensions.

Is there any chance there can be an option to pass to the generator and remove the `.js` on the import/require statements?

Thanks so much for this project!

**Comment by jonnyreeves** [comment]
Sorry for the slow response @graywolf336, this implementation (adding the `.js` file extension to the `require()` statement) is consistent with the protoc javascript generator's output.  If you clone this project and run:

```
npm i && cd test && npm run build
```

You will see that the `test/js_test/generated/examplecom/simple_pb.js` file (which is generated by protoc) contains the following `require()` statements which include the `.js` file extension:

```
var google_protobuf_compiler_plugin_pb = require('google-protobuf/google/protobuf/compiler/plugin_pb.js');
```

Whilst we do have control over the contents of the generated `_pb_service.js` files, and could strip the `.js` extension from there, we would not be able to modify the output from `protoc` - unless there is a `protoc` flag that I'm not aware of that modifies this behaviour?

As a workaround I would suggest running a post-processor over your generated files and stripping the `.js` extension using something like sed.

Please re-open this issue if we can assist further.
