### ISSUE TITLE
Import proto from go src generates wrong imports

### ISSUE THREAD

**Issue by weijiangan** [improbable-eng/ts-protoc-gen#87]
## Problem
When writing Go protobufs, importing proto from go src generates wrong imports

## Steps to reproduce
```proto
import "git.company.com/project/repo/proto/file.proto";
```

generates the following CommonJS import
```js
var git_company_com_project_repo_proto_file_pb = require('./git.company.com/project/repo/proto/file_pb.js');
```
which can't be imported. I noticed non of the examples have imports too

## Expected
Generate correct imports

**Comment by jonnyreeves** [comment]
Thanks for raising, could you elaborate on your expected output please?

**Comment by weijiangan** [comment]
Thanks for the prompt response.

Assuming you're unfamiliar with go, the import system imports packages with the git repo names instead of location on the disk, ie
```
github.com/improbable-eng/ts-protoc-gen
```
instead of according to the location of the file like 
```
./ts-protoc-gen
/var/lib/some/dir
```
If you refer to the steps to reproduce, it generates a `require` that looks like this
```
require('./git.company.com/project/repo/proto/file_pb.js');
``` 
which doesn't exist in the current folder `.`.

Idk if this can be done but I guess we could either generate a valid import path, absolute or relative to the directory of the proto or import all content of the imported proto into the generated stub. What do you think?

**Comment by jonnyreeves** [comment]
Does the proto you are trying to import (`git.company.com/project/repo/proto/file.proto`) exist on your local disk or is protoc fetching it over the network when you compile your protos?

Importing protos in this fashion is not something I've encountered before. A full repro case may help me understand

**Comment by weijiangan** [comment]
@jonnyreeves I will post a repro here as soon as I can

**Comment by jonnyreeves** [comment]
Thanks for adding more info, please can you provide me with a full reproduction of the issue and I can take a look at debugging this ♥️

**Comment by alexanvl** [comment]
1) Proto file `auth.proto`:
```
syntax = "proto3";

package proto;

import "google/api/annotations.proto";

message TokenRequest {
  string address = 1;
}

message TokenResponse {
  string token = 1;
}

message SuccessResponse {
  bool success = 1;
  string error = 2;
}

service Auth {
  rpc GetToken(TokenRequest) returns (TokenResponse) {
    option (google.api.http) = {
      get: "/v1/token/{address}"
    };
  }

  rpc ValidateToken(TokenRequest) returns (SuccessResponse) {
    option (google.api.http) = {
      get: "/v1/validate/{address}"
    };
  }
}
```
2) Generate typescript files using `protoc` and `ts-protoc-gen` plugin:
```
protoc \
	-I ${GOPATH}/src \
	-I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	-I . \
	--plugin="protoc-gen-ts=./node_modules/.bin/protoc-gen-ts" \
	--js_out="import_style=commonjs,binary:./services/ts" \
	--ts_out="service=true:./services/ts" \
	./proto/auth.proto
```
3) Notice that the generated js and ts require the dependency `../google/api/annotations_pb`:
```
// package: proto
// file: proto/auth.proto

import * as jspb from "google-protobuf";
import * as google_api_annotations_pb from "../google/api/annotations_pb";

export class TokenRequest extends jspb.Message {
  getAddress(): string;
  setAddress(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): TokenRequest.AsObject;
  static toObject(includeInstance: boolean, msg: TokenRequest): TokenRequest.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: TokenRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): TokenRequest;
  static deserializeBinaryFromReader(message: TokenRequest, reader: jspb.BinaryReader): TokenRequest;
}

export namespace TokenRequest {
  export type AsObject = {
    address: string,
  }
}

export class TokenResponse extends jspb.Message {
  getToken(): string;
  setToken(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): TokenResponse.AsObject;
  static toObject(includeInstance: boolean, msg: TokenResponse): TokenResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: TokenResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): TokenResponse;
  static deserializeBinaryFromReader(message: TokenResponse, reader: jspb.BinaryReader): TokenResponse;
}

export namespace TokenResponse {
  export type AsObject = {
    token: string,
  }
}

export class SuccessResponse extends jspb.Message {
  getSuccess(): boolean;
  setSuccess(value: boolean): void;

  getError(): string;
  setError(value: string): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): SuccessResponse.AsObject;
  static toObject(includeInstance: boolean, msg: SuccessResponse): SuccessResponse.AsObject;
  static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  static serializeBinaryToWriter(message: SuccessResponse, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): SuccessResponse;
  static deserializeBinaryFromReader(message: SuccessResponse, reader: jspb.BinaryReader): SuccessResponse;
}

export namespace SuccessResponse {
  export type AsObject = {
    success: boolean,
    error: string,
  }
}
```

The issue is that the `../google/api/annotations_pb` package does not exist, and is not a dependency that the js or ts files should import.  It is only imported in the `.proto` spec for `grpc-gateway` support.

**Comment by jonnyreeves** [comment]
To clarify, the expected result is that this import statement is not
present in the generated code?

**Comment by alexanvl** [comment]
```
To clarify, the expected result is that this import statement is not
present in the generated code?
```
Correct.  Thanks for your help!

**Comment by jonny-improbable** [comment]
Hey @alexanvl, a quick fix/workaround for your issue is to add `google/api/annotations.proto` to the `WellKnownTypesMap`; I'd accept a PR for this although I appreciate we probably need a better long term solution here.

**Comment by alexanvl** [comment]
Ok, thanks.  I'l look into it.

**Comment by amricko0b** [comment]
Stuck into the same issue.
Any progress here?

**Comment by jonnyreeves** [comment]
@amricko0b can you confirm which import is failing for you please?

**Comment by draeron** [comment]
is there a work around for this issue, i've been trying to setup a grpcweb with a gateway as @alexanvl and i bumped into this problem too.

**Comment by alexanvl** [comment]
I switched to https://github.com/tmc/grpcutil/tree/master/protoc-gen-tstypes

**Comment by Emixam23** [comment]
Still nothing? :/

**Comment by Bluskript** [comment]
I have this issue when using https://github.com/envoyproxy/protoc-gen-validate
the key benefit of protobufs is that on both client and server, the definitions are the same. Although I import `protoc-gen-validate` on the server, I do not want it to be required on the client side.

**Comment by Elojah** [comment]
Any update on this issue ? I have same issue with local imports.

`auth.proto`
```
  ...
  import "github.com/.../user.proto";
  ...
```

(works well generating `.go` files thanks to `-I=$(GOPATH)/src`)

and in generated `.ts` file:
```
  import * as github_com_..._user_pb from "./github.com/.../user_pb";
```

Obviously this path starting with `./github.com` is not valid.
