### ISSUE TITLE
More graceful way to cancel stream?

### ISSUE THREAD

**Issue by mwei0210** [improbable-eng/ts-protoc-gen#88]
After calling [stream.cancel()](https://github.com/improbable-eng/ts-protoc-gen/blob/master/examples/generated/orphan_pb_service.d.ts#L36), the stream still continue to return data causing console to throw error

```
Uncaught TypeError: Cannot read property 'data' of null
```
Maybe an example if there is way to do that? thanks!

**Comment by easyCZ** [comment]
Hi @mwei0210,

As far as I know, this appears to be an error in the underlying protobuf implementation rather than in ts-protoc-gen. This project only generates types on top of the generated implementation.

Will close. Let me know if my assumption is incorrect and I'll reopen.

**Comment by mwei0210** [comment]
@jonnyreeves ah i see. will that be fixed in the near future?

**Comment by jonnyreeves** [comment]
I do not have any free time at present, however the patch is unlikely to be complicated.

If you are happy to volunteer, raising a bug report on the grpc-web-client project would be a great starting point

Thanks
