### ISSUE TITLE
Wrappers does not work

### ISSUE THREAD

**Issue by zolo** [improbable-eng/ts-protoc-gen#89]
... Under node 8. It would appear there is an issue with the JavaScript generated by protoc

Input definition:

```
syntax = "proto3";
import "google/protobuf/wrappers.proto";

message test 
{
    google.protobuf.StringValue mystring = 1;
}
```

Causes this at runtime:

```
  TypeError: c.toArray is not a function

  Function.jspb.Message.setWrapperField (node_modules/google-protobuf/google-protobuf.js:207:86)
```

**Comment by easyCZ** [comment]
Hi @zolo,

Could you please provide more details? How did you generate the protos? Could we have a script/snippet? What is your JS/TS code doing? How is it invoking the call? If you could provide an example repo/reproducible snippet we can help diagnose this issue better.

**Comment by zolo** [comment]
I followed the instructions here to the letter: https://github.com/improbable-eng/ts-protoc-gen

Adding a google.protobuf.StringValue makes it fail with the above error.

**Comment by jonnyreeves** [comment]
Which browser are you using? I'm guessing that the code generated by protoc contains some unsupported prototype methods which you may need to polyfill in legacy browsers

**Comment by zolo** [comment]
@jonnyreeves no browser, this is Node.js v8.9.0

**Comment by jonnyreeves** [comment]
Interesting. Could you help debug this by looking at the stack trace and
determining which object the `toArray` method is attached to?

**Comment by zolo** [comment]
Sorry, due to time constraints I had to switch to `protobufjs` and I don't longer have the ts-protoc-gen project.

**Comment by jonnyreeves** [comment]
Hmm. I just checked and we actually run our tests under node 8 so I'm very intrigued as to how you are experiencing this failure.

I'm going to close this issue now as I would not know when to start with reproducing this issue but if anyone else encounters it, please can you provide a repro and we can dig in

Thanks
