### ISSUE TITLE
Combine output in a single d.ts file 

### ISSUE THREAD

**Issue by ivoshabarkov** [improbable-eng/ts-protoc-gen#93]
Hi,

I cannot seem to find a way to combine output from multiple proto files to a single d.ts file.
I need that because the messages in all my proto files are in the same namespace.
Thank you.

**Comment by jonnyreeves** [comment]
@ivoshabarkov I don't think this is something we would want to add to ts-protoc-gen as it will add additional complexity. Perhaps [dts-bundle](https://github.com/TypeStrong/dts-bundle#all-dts-files) meets your needs when used as a post-build step?
