### ISSUE TITLE
Enum case not preserved 

### ISSUE THREAD

**Issue by screenpunch** [improbable-eng/ts-protoc-gen#94]
I have a enum defined as 

`enum ProfileTypeETOS { 
    YieldProfile = 1; 
    Profit = 2; 
}`

The generated TypeScript is

`export enum ProfileTypeETOS {
  YIELDPROFILE = 1,
  PROFIT = 2,
}`

You will notice that I have lost the CamelCase enums, is there a way to preserve the case?

* Edit: I've seen commit https://github.com/improbable-eng/ts-protoc-gen/commit/bd7f65839264de76c8c4041e7c34d942df27dc5c, can this be optional?

**Comment by jonny-improbable** [comment]
Whilst we could make bd7f658 optional it would not affect the JavaScript output emitted by the protoc compiler. See #21 for more details and feel free to re-open if I'm missing something.

Thanks.
