### ISSUE TITLE
Compilation issues...

### ISSUE THREAD

**Issue by gagranov** [improbable-eng/ts-protoc-gen#95]
Hi,

I am not expert in TypeScript or Angular - sorry!
I did generate your nice *.ts.d files - thanks a lot! 
But ng complains about two things - unknown properties - I have commented them out,
but there is still error per each message:

**Type 'any' is not a constructor function type.**

Anything I can do to fix these errors?

Thanks,
Gennady

import * as jspb from "google-protobuf";

export class BooleanValue extends jspb.Message {
  hasValue(): boolean;
  clearValue(): void;
  getValue(): boolean | undefined;
  setValue(value: boolean): void;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): BooleanValue.AsObject;
  static toObject(includeInstance: boolean, msg: BooleanValue): BooleanValue.AsObject;
  // static extensions: {[key: number]: jspb.ExtensionFieldInfo<jspb.Message>};
  // static extensionsBinary: {[key: number]: jspb.ExtensionFieldBinaryInfo<jspb.Message>};
  // static serializeBinaryToWriter(message: BooleanValue, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): BooleanValue;
  // static deserializeBinaryFromReader(message: BooleanValue, reader: jspb.BinaryReader): BooleanValue;
}

**Comment by jonny-improbable** [comment]
Closing as no repro was provided.
